from ..defines import *
from ..items import ItemPool, Item, ClassMod, BanditGrenade, MultiBarrelWeapon

# fmt: off

Items = (
    ItemPool("Blue Bloodthirster / Blaster / Cowgirl / Brotrap / CEO / Big Game Hunter", Hint.BlueClassMod,
        ClassMod("GD_Cork_ItemGrades.ClassMods.BalDef_ClassMod_Gladiator_03_Rare", 0, Character.Gladiator),
        ClassMod("GD_Cork_ItemGrades.ClassMods.BalDef_ClassMod_Enforcer_03_Rare", 0, Character.Enforcer),
        ClassMod("GD_Cork_ItemGrades.ClassMods.BalDef_ClassMod_Lawbringer_03_Rare", 0, Character.Lawbringer),
        ClassMod("GD_Cork_ItemGrades.ClassMods.BalDef_ClassMod_Prototype_03_Rare", 0, Character.Prototype),
        ClassMod("GD_Quince_ItemGrades.ClassMods.BalDef_ClassMod_Doppelganger_03_Rare", 0, Character.Doppelganger),
        ClassMod("GD_Crocus_ItemGrades.ClassMods.BalDef_ClassMod_Baroness_03_Rare", 0, Character.Baroness),
    ),
    ItemPool("Blue Cannoness / Obliterator / Crapshooter / Factory Second / Entrepreneur / Sport Hunter", Hint.BlueClassMod,
        ClassMod("GD_Cork_ItemGrades.ClassMods.BalDef_ClassMod_Gladiator_03_Rare", 1, Character.Gladiator),
        ClassMod("GD_Cork_ItemGrades.ClassMods.BalDef_ClassMod_Enforcer_03_Rare", 1, Character.Enforcer),
        ClassMod("GD_Cork_ItemGrades.ClassMods.BalDef_ClassMod_Lawbringer_03_Rare", 1, Character.Lawbringer),
        ClassMod("GD_Cork_ItemGrades.ClassMods.BalDef_ClassMod_Prototype_03_Rare", 1, Character.Prototype),
        ClassMod("GD_Quince_ItemGrades.ClassMods.BalDef_ClassMod_Doppelganger_03_Rare", 1, Character.Doppelganger),
        ClassMod("GD_Crocus_ItemGrades.ClassMods.BalDef_ClassMod_Baroness_03_Rare", 1, Character.Baroness),
    ),
    ItemPool("Blue Defender / Equalizer / Desperado / Sapper / Hero / Crème de la Crème", Hint.BlueClassMod,
        ClassMod("GD_Cork_ItemGrades.ClassMods.BalDef_ClassMod_Gladiator_03_Rare", 2, Character.Gladiator),
        ClassMod("GD_Cork_ItemGrades.ClassMods.BalDef_ClassMod_Enforcer_03_Rare", 2, Character.Enforcer),
        ClassMod("GD_Cork_ItemGrades.ClassMods.BalDef_ClassMod_Lawbringer_03_Rare", 2, Character.Lawbringer),
        ClassMod("GD_Cork_ItemGrades.ClassMods.BalDef_ClassMod_Prototype_03_Rare", 2, Character.Prototype),
        ClassMod("GD_Quince_ItemGrades.ClassMods.BalDef_ClassMod_Doppelganger_03_Rare", 2, Character.Doppelganger),
        ClassMod("GD_Crocus_ItemGrades.ClassMods.BalDef_ClassMod_Baroness_03_Rare", 2, Character.Baroness),
    ),
    ItemPool("Blue Dominator / Fighter / The Kid / Madtrap / Paragon / Privileged", Hint.BlueClassMod,
        ClassMod("GD_Cork_ItemGrades.ClassMods.BalDef_ClassMod_Gladiator_03_Rare", 3, Character.Gladiator),
        ClassMod("GD_Cork_ItemGrades.ClassMods.BalDef_ClassMod_Enforcer_03_Rare", 3, Character.Enforcer),
        ClassMod("GD_Cork_ItemGrades.ClassMods.BalDef_ClassMod_Lawbringer_03_Rare", 3, Character.Lawbringer),
        ClassMod("GD_Cork_ItemGrades.ClassMods.BalDef_ClassMod_Prototype_03_Rare", 3, Character.Prototype),
        ClassMod("GD_Quince_ItemGrades.ClassMods.BalDef_ClassMod_Doppelganger_03_Rare", 3, Character.Doppelganger),
        ClassMod("GD_Crocus_ItemGrades.ClassMods.BalDef_ClassMod_Baroness_03_Rare", 3, Character.Baroness),
    ),
    ItemPool("Blue Dragon / Golem / Bounty Hunter / Overclocker / VIP / Blue Blood", Hint.BlueClassMod,
        ClassMod("GD_Cork_ItemGrades.ClassMods.BalDef_ClassMod_Gladiator_03_Rare", 4, Character.Gladiator),
        ClassMod("GD_Cork_ItemGrades.ClassMods.BalDef_ClassMod_Enforcer_03_Rare", 4, Character.Enforcer),
        ClassMod("GD_Cork_ItemGrades.ClassMods.BalDef_ClassMod_Lawbringer_03_Rare", 4, Character.Lawbringer),
        ClassMod("GD_Cork_ItemGrades.ClassMods.BalDef_ClassMod_Prototype_03_Rare", 4, Character.Prototype),
        ClassMod("GD_Quince_ItemGrades.ClassMods.BalDef_ClassMod_Doppelganger_03_Rare", 4, Character.Doppelganger),
        ClassMod("GD_Crocus_ItemGrades.ClassMods.BalDef_ClassMod_Baroness_03_Rare", 4, Character.Baroness),
    ),
    ItemPool("Blue Femme Fatale / Howitzer / Rustler / Piñata / Antagonist / Gentry", Hint.BlueClassMod,
        ClassMod("GD_Cork_ItemGrades.ClassMods.BalDef_ClassMod_Gladiator_03_Rare", 5, Character.Gladiator),
        ClassMod("GD_Cork_ItemGrades.ClassMods.BalDef_ClassMod_Enforcer_03_Rare", 5, Character.Enforcer),
        ClassMod("GD_Cork_ItemGrades.ClassMods.BalDef_ClassMod_Lawbringer_03_Rare", 5, Character.Lawbringer),
        ClassMod("GD_Cork_ItemGrades.ClassMods.BalDef_ClassMod_Prototype_03_Rare", 5, Character.Prototype),
        ClassMod("GD_Quince_ItemGrades.ClassMods.BalDef_ClassMod_Doppelganger_03_Rare", 5, Character.Doppelganger),
        ClassMod("GD_Crocus_ItemGrades.ClassMods.BalDef_ClassMod_Baroness_03_Rare", 5, Character.Baroness),
    ),
    ItemPool("Blue Gladiatrix / Mauler / The Lone Star / Loose Cannon / Role Model / Lady", Hint.BlueClassMod,
        ClassMod("GD_Cork_ItemGrades.ClassMods.BalDef_ClassMod_Gladiator_03_Rare", 6, Character.Gladiator),
        ClassMod("GD_Cork_ItemGrades.ClassMods.BalDef_ClassMod_Enforcer_03_Rare", 6, Character.Enforcer),
        ClassMod("GD_Cork_ItemGrades.ClassMods.BalDef_ClassMod_Lawbringer_03_Rare", 6, Character.Lawbringer),
        ClassMod("GD_Cork_ItemGrades.ClassMods.BalDef_ClassMod_Prototype_03_Rare", 6, Character.Prototype),
        ClassMod("GD_Quince_ItemGrades.ClassMods.BalDef_ClassMod_Doppelganger_03_Rare", 6, Character.Doppelganger),
        ClassMod("GD_Crocus_ItemGrades.ClassMods.BalDef_ClassMod_Baroness_03_Rare", 6, Character.Baroness),
    ),
    ItemPool("Blue Protector / Mech / Sheriff / Roboninja / Protagonist / Master", Hint.BlueClassMod,
        ClassMod("GD_Cork_ItemGrades.ClassMods.BalDef_ClassMod_Gladiator_03_Rare", 7, Character.Gladiator),
        ClassMod("GD_Cork_ItemGrades.ClassMods.BalDef_ClassMod_Enforcer_03_Rare", 7, Character.Enforcer),
        ClassMod("GD_Cork_ItemGrades.ClassMods.BalDef_ClassMod_Lawbringer_03_Rare", 7, Character.Lawbringer),
        ClassMod("GD_Cork_ItemGrades.ClassMods.BalDef_ClassMod_Prototype_03_Rare", 7, Character.Prototype),
        ClassMod("GD_Quince_ItemGrades.ClassMods.BalDef_ClassMod_Doppelganger_03_Rare", 7, Character.Doppelganger),
        ClassMod("GD_Crocus_ItemGrades.ClassMods.BalDef_ClassMod_Baroness_03_Rare", 7, Character.Baroness),
    ),
    ItemPool("Blue Storm / Scorcher / Six-Shooter / Short Circuit / Best Man / Mistress", Hint.BlueClassMod,
        ClassMod("GD_Cork_ItemGrades.ClassMods.BalDef_ClassMod_Gladiator_03_Rare", 8, Character.Gladiator),
        ClassMod("GD_Cork_ItemGrades.ClassMods.BalDef_ClassMod_Enforcer_03_Rare", 8, Character.Enforcer),
        ClassMod("GD_Cork_ItemGrades.ClassMods.BalDef_ClassMod_Lawbringer_03_Rare", 8, Character.Lawbringer),
        ClassMod("GD_Cork_ItemGrades.ClassMods.BalDef_ClassMod_Prototype_03_Rare", 8, Character.Prototype),
        ClassMod("GD_Quince_ItemGrades.ClassMods.BalDef_ClassMod_Doppelganger_03_Rare", 8, Character.Doppelganger),
        ClassMod("GD_Crocus_ItemGrades.ClassMods.BalDef_ClassMod_Baroness_03_Rare", 8, Character.Baroness),
    ),
    ItemPool("Blue Hologram / Projector / Illusion / Glitch / Projection / High Definition", Hint.BlueClassMod,
        ClassMod("GD_Petunia_ItemGrades.ClassMods.BalDef_Pet_ClassMod_Gladiator_03_Rare", 0, Character.Gladiator, content=Tag.Holodome),
        ClassMod("GD_Petunia_ItemGrades.ClassMods.BalDef_Pet_ClassMod_Enforcer_03_Rare", 0, Character.Enforcer, content=Tag.Holodome),
        ClassMod("GD_Petunia_ItemGrades.ClassMods.BalDef_Pet_ClassMod_Lawbringer_03_Rare", 0, Character.Lawbringer, content=Tag.Holodome),
        ClassMod("GD_Petunia_ItemGrades.ClassMods.BalDef_Pet_ClassMod_Prototype_03_Rare", 0, Character.Prototype, content=Tag.Holodome),
        ClassMod("GD_Petunia_ItemGrades.ClassMods.BalDef_Pet_ClassMod_Doppel_03_Rare", 0, Character.Doppelganger, content=Tag.Holodome),
        ClassMod("GD_Crocus_ItemGrades.ClassMods.BalDef_Pet_ClassMod_Baroness_03_Rare", 0, Character.Baroness, content=Tag.Holodome),
    ),

    ItemPool("Purple Bloodthirster / Blaster / Cowgirl / Brotrap / CEO / Big Game Hunter", Hint.PurpleClassMod,
        ClassMod("GD_Cork_ItemGrades.ClassMods.BalDef_ClassMod_Gladiator_04_VeryRare", 0, Character.Gladiator),
        ClassMod("GD_Cork_ItemGrades.ClassMods.BalDef_ClassMod_Enforcer_04_VeryRare", 0, Character.Enforcer),
        ClassMod("GD_Cork_ItemGrades.ClassMods.BalDef_ClassMod_Lawbringer_04_VeryRare", 0, Character.Lawbringer),
        ClassMod("GD_Cork_ItemGrades.ClassMods.BalDef_ClassMod_Prototype_04_VeryRare", 0, Character.Prototype),
        ClassMod("GD_Quince_ItemGrades.ClassMods.BalDef_ClassMod_Doppelganger_04_VeryRare", 0, Character.Doppelganger),
        ClassMod("GD_Crocus_ItemGrades.ClassMods.BalDef_ClassMod_Baroness_04_VeryRare", 0, Character.Baroness),
    ),
    ItemPool("Purple Cannoness / Obliterator / Crapshooter / Factory Second / Entrepreneur / Sport Hunter", Hint.PurpleClassMod,
        ClassMod("GD_Cork_ItemGrades.ClassMods.BalDef_ClassMod_Gladiator_04_VeryRare", 1, Character.Gladiator),
        ClassMod("GD_Cork_ItemGrades.ClassMods.BalDef_ClassMod_Enforcer_04_VeryRare", 1, Character.Enforcer),
        ClassMod("GD_Cork_ItemGrades.ClassMods.BalDef_ClassMod_Lawbringer_04_VeryRare", 1, Character.Lawbringer),
        ClassMod("GD_Cork_ItemGrades.ClassMods.BalDef_ClassMod_Prototype_04_VeryRare", 1, Character.Prototype),
        ClassMod("GD_Quince_ItemGrades.ClassMods.BalDef_ClassMod_Doppelganger_04_VeryRare", 1, Character.Doppelganger),
        ClassMod("GD_Crocus_ItemGrades.ClassMods.BalDef_ClassMod_Baroness_04_VeryRare", 1, Character.Baroness),
    ),
    ItemPool("Purple Defender / Equalizer / Desperado / Sapper / Hero / Crème de la Crème", Hint.PurpleClassMod,
        ClassMod("GD_Cork_ItemGrades.ClassMods.BalDef_ClassMod_Gladiator_04_VeryRare", 2, Character.Gladiator),
        ClassMod("GD_Cork_ItemGrades.ClassMods.BalDef_ClassMod_Enforcer_04_VeryRare", 2, Character.Enforcer),
        ClassMod("GD_Cork_ItemGrades.ClassMods.BalDef_ClassMod_Lawbringer_04_VeryRare", 2, Character.Lawbringer),
        ClassMod("GD_Cork_ItemGrades.ClassMods.BalDef_ClassMod_Prototype_04_VeryRare", 2, Character.Prototype),
        ClassMod("GD_Quince_ItemGrades.ClassMods.BalDef_ClassMod_Doppelganger_04_VeryRare", 2, Character.Doppelganger),
        ClassMod("GD_Crocus_ItemGrades.ClassMods.BalDef_ClassMod_Baroness_04_VeryRare", 2, Character.Baroness),
    ),
    ItemPool("Purple Dominator / Fighter / The Kid / Madtrap / Paragon / Privileged", Hint.PurpleClassMod,
        ClassMod("GD_Cork_ItemGrades.ClassMods.BalDef_ClassMod_Gladiator_04_VeryRare", 3, Character.Gladiator),
        ClassMod("GD_Cork_ItemGrades.ClassMods.BalDef_ClassMod_Enforcer_04_VeryRare", 3, Character.Enforcer),
        ClassMod("GD_Cork_ItemGrades.ClassMods.BalDef_ClassMod_Lawbringer_04_VeryRare", 3, Character.Lawbringer),
        ClassMod("GD_Cork_ItemGrades.ClassMods.BalDef_ClassMod_Prototype_04_VeryRare", 3, Character.Prototype),
        ClassMod("GD_Quince_ItemGrades.ClassMods.BalDef_ClassMod_Doppelganger_04_VeryRare", 3, Character.Doppelganger),
        ClassMod("GD_Crocus_ItemGrades.ClassMods.BalDef_ClassMod_Baroness_04_VeryRare", 3, Character.Baroness),
    ),
    ItemPool("Purple Dragon / Golem / Bounty Hunter / Overclocker / VIP / Blue Blood", Hint.PurpleClassMod,
        ClassMod("GD_Cork_ItemGrades.ClassMods.BalDef_ClassMod_Gladiator_04_VeryRare", 4, Character.Gladiator),
        ClassMod("GD_Cork_ItemGrades.ClassMods.BalDef_ClassMod_Enforcer_04_VeryRare", 4, Character.Enforcer),
        ClassMod("GD_Cork_ItemGrades.ClassMods.BalDef_ClassMod_Lawbringer_04_VeryRare", 4, Character.Lawbringer),
        ClassMod("GD_Cork_ItemGrades.ClassMods.BalDef_ClassMod_Prototype_04_VeryRare", 4, Character.Prototype),
        ClassMod("GD_Quince_ItemGrades.ClassMods.BalDef_ClassMod_Doppelganger_04_VeryRare", 4, Character.Doppelganger),
        ClassMod("GD_Crocus_ItemGrades.ClassMods.BalDef_ClassMod_Baroness_04_VeryRare", 4, Character.Baroness),
    ),
    ItemPool("Purple Femme Fatale / Howitzer / Rustler / Piñata / Antagonist / Gentry", Hint.PurpleClassMod,
        ClassMod("GD_Cork_ItemGrades.ClassMods.BalDef_ClassMod_Gladiator_04_VeryRare", 5, Character.Gladiator),
        ClassMod("GD_Cork_ItemGrades.ClassMods.BalDef_ClassMod_Enforcer_04_VeryRare", 5, Character.Enforcer),
        ClassMod("GD_Cork_ItemGrades.ClassMods.BalDef_ClassMod_Lawbringer_04_VeryRare", 5, Character.Lawbringer),
        ClassMod("GD_Cork_ItemGrades.ClassMods.BalDef_ClassMod_Prototype_04_VeryRare", 5, Character.Prototype),
        ClassMod("GD_Quince_ItemGrades.ClassMods.BalDef_ClassMod_Doppelganger_04_VeryRare", 5, Character.Doppelganger),
        ClassMod("GD_Crocus_ItemGrades.ClassMods.BalDef_ClassMod_Baroness_04_VeryRare", 5, Character.Baroness),
    ),
    ItemPool("Purple Gladiatrix / Mauler / The Lone Star / Loose Cannon / Role Model / Lady", Hint.PurpleClassMod,
        ClassMod("GD_Cork_ItemGrades.ClassMods.BalDef_ClassMod_Gladiator_04_VeryRare", 6, Character.Gladiator),
        ClassMod("GD_Cork_ItemGrades.ClassMods.BalDef_ClassMod_Enforcer_04_VeryRare", 6, Character.Enforcer),
        ClassMod("GD_Cork_ItemGrades.ClassMods.BalDef_ClassMod_Lawbringer_04_VeryRare", 6, Character.Lawbringer),
        ClassMod("GD_Cork_ItemGrades.ClassMods.BalDef_ClassMod_Prototype_04_VeryRare", 6, Character.Prototype),
        ClassMod("GD_Quince_ItemGrades.ClassMods.BalDef_ClassMod_Doppelganger_04_VeryRare", 6, Character.Doppelganger),
        ClassMod("GD_Crocus_ItemGrades.ClassMods.BalDef_ClassMod_Baroness_04_VeryRare", 6, Character.Baroness),
    ),
    ItemPool("Purple Protector / Mech / Sheriff / Roboninja / Protagonist / Master", Hint.PurpleClassMod,
        ClassMod("GD_Cork_ItemGrades.ClassMods.BalDef_ClassMod_Gladiator_04_VeryRare", 7, Character.Gladiator),
        ClassMod("GD_Cork_ItemGrades.ClassMods.BalDef_ClassMod_Enforcer_04_VeryRare", 7, Character.Enforcer),
        ClassMod("GD_Cork_ItemGrades.ClassMods.BalDef_ClassMod_Lawbringer_04_VeryRare", 7, Character.Lawbringer),
        ClassMod("GD_Cork_ItemGrades.ClassMods.BalDef_ClassMod_Prototype_04_VeryRare", 7, Character.Prototype),
        ClassMod("GD_Quince_ItemGrades.ClassMods.BalDef_ClassMod_Doppelganger_04_VeryRare", 7, Character.Doppelganger),
        ClassMod("GD_Crocus_ItemGrades.ClassMods.BalDef_ClassMod_Baroness_04_VeryRare", 7, Character.Baroness),
    ),
    ItemPool("Purple Storm / Scorcher / Six-Shooter / Short Circuit / Best Man / Mistress", Hint.PurpleClassMod,
        ClassMod("GD_Cork_ItemGrades.ClassMods.BalDef_ClassMod_Gladiator_04_VeryRare", 8, Character.Gladiator),
        ClassMod("GD_Cork_ItemGrades.ClassMods.BalDef_ClassMod_Enforcer_04_VeryRare", 8, Character.Enforcer),
        ClassMod("GD_Cork_ItemGrades.ClassMods.BalDef_ClassMod_Lawbringer_04_VeryRare", 8, Character.Lawbringer),
        ClassMod("GD_Cork_ItemGrades.ClassMods.BalDef_ClassMod_Prototype_04_VeryRare", 8, Character.Prototype),
        ClassMod("GD_Quince_ItemGrades.ClassMods.BalDef_ClassMod_Doppelganger_04_VeryRare", 8, Character.Doppelganger),
        ClassMod("GD_Crocus_ItemGrades.ClassMods.BalDef_ClassMod_Baroness_04_VeryRare", 8, Character.Baroness),
    ),
    ItemPool("Purple Hologram / Projector / Illusion / Glitch / Projection / High Definition", Hint.PurpleClassMod,
        ClassMod("GD_Petunia_ItemGrades.ClassMods.BalDef_Pet_ClassMod_Gladiator_04_VeryRare", 0, Character.Gladiator, content=Tag.Holodome),
        ClassMod("GD_Petunia_ItemGrades.ClassMods.BalDef_Pet_ClassMod_Enforcer_04_VeryRare", 0, Character.Enforcer, content=Tag.Holodome),
        ClassMod("GD_Petunia_ItemGrades.ClassMods.BalDef_Pet_ClassMod_Lawbringer_04_VeryRare", 0, Character.Lawbringer, content=Tag.Holodome),
        ClassMod("GD_Petunia_ItemGrades.ClassMods.BalDef_Pet_ClassMod_Prototype_04_VeryRare", 0, Character.Prototype, content=Tag.Holodome),
        ClassMod("GD_Petunia_ItemGrades.ClassMods.BalDef_Pet_ClassMod_Doppel_04_VeryRare", 0, Character.Doppelganger, content=Tag.Holodome),
        ClassMod("GD_Crocus_ItemGrades.ClassMods.BalDef_Pet_ClassMod_Baroness_04_VeryRare", 0, Character.Baroness, content=Tag.Holodome),
    ),

    ItemPool("Celestial Gladiator / Enforcer / Lawbringer / Fragtrap / Doppelganger / Baroness", Hint.LegendaryClassMod,
        ClassMod("GD_Cork_ItemGrades.ClassMods.BalDef_ClassMod_Gladiator_05_Legendary", 0, Character.Gladiator),
        ClassMod("GD_Cork_ItemGrades.ClassMods.BalDef_ClassMod_Enforcer_05_Legendary", 0, Character.Enforcer),
        ClassMod("GD_Cork_ItemGrades.ClassMods.BalDef_ClassMod_Lawbringer_05_Legendary", 0, Character.Lawbringer),
        ClassMod("GD_Cork_ItemGrades.ClassMods.BalDef_ClassMod_Prototype_05_Legendary", 0, Character.Prototype),
        ClassMod("GD_Quince_ItemGrades.ClassMods.BalDef_ClassMod_Doppelganger_05_Legendary", 0, Character.Doppelganger),
        ClassMod("GD_Crocus_ItemGrades.ClassMods.BalDef_ClassMod_Baroness_05_Legendary", 0, Character.Baroness),
    ),
    ItemPool("Eridian Vanquisher", Hint.LegendaryClassMod,
        ClassMod("GD_Cork_ItemGrades.ClassMods.BalDef_ClassMod_Gladiator_06_EridianVanquisher", 0, Character.Gladiator),
        ClassMod("GD_Cork_ItemGrades.ClassMods.BalDef_ClassMod_Enforcer_06_EridianVanquisher", 0, Character.Enforcer),
        ClassMod("GD_Cork_ItemGrades.ClassMods.BalDef_ClassMod_Lawbringer_06_EridianVanquisher", 0, Character.Lawbringer),
        ClassMod("GD_Cork_ItemGrades.ClassMods.BalDef_ClassMod_Prototype_06_EridianVanquisher", 0, Character.Prototype),
        ClassMod("GD_Quince_ItemGrades.ClassMods.BalDef_ClassMod_Doppelganger_06_EridianVanquisher", 0, Character.Doppelganger),
        ClassMod("GD_Crocus_ItemGrades.ClassMods.BalDef_ClassMod_Baroness_06_EridianVanquisher", 0, Character.Baroness),
    ),
    ItemPool("Chronicler Of Elpis", Hint.LegendaryClassMod,
        ClassMod("GD_Petunia_ItemGrades.ClassMods.BalDef_Pet_ClassMod_Gladiator_07_Chronicler", 0, Character.Gladiator, content=Tag.Holodome),
        ClassMod("GD_Petunia_ItemGrades.ClassMods.BalDef_Pet_ClassMod_Enforcer_07_Chronicler", 0, Character.Enforcer, content=Tag.Holodome),
        ClassMod("GD_Petunia_ItemGrades.ClassMods.BalDef_Pet_ClassMod_Lawbringer_07_Chronicler", 0, Character.Lawbringer, content=Tag.Holodome),
        ClassMod("GD_Petunia_ItemGrades.ClassMods.BalDef_Pet_ClassMod_Prototype_07_Chronicler", 0, Character.Prototype, content=Tag.Holodome),
        ClassMod("GD_Petunia_ItemGrades.ClassMods.BalDef_Pet_ClassMod_Doppel_07_Chronicler", 0, Character.Doppelganger, content=Tag.Holodome),
        ClassMod("GD_Crocus_ItemGrades.ClassMods.BalDef_ClassMod_Baroness_07_ChroniclerOfElpis", 0, Character.Baroness, content=Tag.Holodome),
    ),

    ItemPool("Major Tom", Hint.LegendaryAR, Item("gd_cork_weap_assaultrifle.A_Weapons_Legendary.AR_Dahl_5_MajorTom")),
    ItemPool("Hammer Buster II", Hint.LegendaryAR, Item("gd_cork_weap_assaultrifle.A_Weapons_Legendary.AR_Jakobs_5_HammerBreaker")),
    ItemPool("KerBoom", Hint.LegendaryAR, Item("gd_cork_weap_assaultrifle.A_Weapons_Legendary.AR_Torgue_5_KerBoom")),
    ItemPool("Shredifier", Hint.LegendaryAR, Item("gd_cork_weap_assaultrifle.A_Weapons_Legendary.AR_Vladof_5_Shredifier")),

    ItemPool("Wallop", Hint.UniqueAR, Item("gd_cork_weap_assaultrifle.A_Weapons_Unique.AR_Jakobs_3_Wallop")),
    ItemPool("Hail", Hint.UniqueAR, Item("gd_cork_weap_assaultrifle.A_Weapons_Unique.AR_Vladof_3_Hail")),
    ItemPool("Ice Scream", Hint.UniqueAR, Item("gd_cork_weap_assaultrifle.A_Weapons_Unique.AR_Vladof_3_IceScream")),
    ItemPool("Ol' Painful", Hint.UniqueAR, Item("gd_cork_weap_assaultrifle.A_Weapons_Unique.AR_Vladof_3_OldPainful")),

    ItemPool("Cat o' Nine Tails", Hint.LegendaryLaser, Item("GD_Cork_Weap_Lasers.A_Weapons_Legendary.Laser_Dahl_5_Ricochet")),
    ItemPool("The ZX-1", Hint.LegendaryLaser, Item("GD_Cork_Weap_Lasers.A_Weapons_Legendary.Laser_Dahl_5_ZX1")),
    ItemPool("Excalibastard", Hint.LegendaryLaser, Item("GD_Cork_Weap_Lasers.A_Weapons_Legendary.Laser_Old_Hyperion_5_Excalibastard")),
    ItemPool("Min Min Lighter", Hint.LegendaryLaser, Item("GD_Cork_Weap_Lasers.A_Weapons_Legendary.Laser_Tediore_5_Tesla")),

    ItemPool("Firestarta", Hint.UniqueLaser, Item("GD_Cork_Weap_Lasers.A_Weapons_Unique.Laser_Dahl_3_Firestarta")),
    ItemPool("Mining Laser", Hint.UniqueLaser, Item("GD_Cork_Weap_Lasers.A_Weapons_Unique.Laser_Hyperion_3_Mining")),
    ItemPool("Lazlo's Freezeasy", Hint.UniqueLaser, Item("GD_Cork_Weap_Lasers.A_Weapons_Unique.Laser_Maliwan_3_Blizzard")),
    ItemPool("Vibra-Pulse", Hint.UniqueLaser, Item("GD_Cork_Weap_Lasers.A_Weapons_Unique.Laser_Maliwan_3_VibraPulse")),
    ItemPool("E-GUN", Hint.UniqueLaser, Item("GD_Cork_Weap_Lasers.A_Weapons_Unique.Laser_Maliwan_4_Egun")),
    ItemPool("Ol' Rosie", Hint.UniqueLaser, Item("GD_Cork_Weap_Lasers.A_Weapons_Unique.Laser_Maliwan_4_Rosie")),
    ItemPool("Toby's Bright Spadroon", Hint.UniqueLaser, Item("GD_Cork_Weap_Lasers.A_Weapons_Unique.Laser_Maliwan_4_SavorySideSaber")),
    ItemPool("Vandergraffen", Hint.UniqueLaser, Item("GD_Cork_Weap_Lasers.A_Weapons_Unique.Laser_Tediore_3_Vandergraffen")),

    ItemPool("Badaboom", Hint.UniqueLauncher, Item("GD_Cork_Weap_Launchers.A_Weapons_Legendary.RL_Bandit_5_BadaBoom")),
    ItemPool("Thingy", Hint.UniqueLauncher, Item("GD_Cork_Weap_Launchers.A_Weapons_Legendary.RL_Bandit_5_Thingy")),
    ItemPool("Cryophobia", Hint.UniqueLauncher, Item("GD_Cork_Weap_Launchers.A_Weapons_Legendary.RL_Maliwan_5_Cryophobia")),
    ItemPool("Nukem", Hint.UniqueLauncher, Item("GD_Cork_Weap_Launchers.A_Weapons_Legendary.RL_Torgue_5_Nukem")),
    ItemPool("Mongol", Hint.UniqueLauncher, Item("GD_Cork_Weap_Launchers.A_Weapons_Legendary.RL_Vladof_5_Mongol")),
    ItemPool("Volt Thrower", Hint.UniqueLauncher, Item("GD_Cork_Weap_Launchers.A_Weapons_Unique.RL_Tediore_3_Rocketeer")),

    ItemPool("Zim", Hint.LegendaryPistol, Item("GD_Cork_Weap_Pistol.A_Weapons_Legendary.Pistol_Bandit_5_Zim")),
    ItemPool("Blowfly", Hint.LegendaryPistol, Item("GD_Cork_Weap_Pistol.A_Weapons_Legendary.Pistol_Dahl_5_Blowfly")),
    ItemPool("Maggie", Hint.LegendaryPistol, Item("GD_Cork_Weap_Pistol.A_Weapons_Legendary.Pistol_Jakobs_5_Maggie")),
    ItemPool("Shooterang", Hint.LegendaryPistol, Item("GD_Cork_Weap_Pistol.A_Weapons_Legendary.Pistol_Tediore_5_Shooterang")),
    ItemPool("88 Fragnum", Hint.LegendaryPistol, Item("GD_Cork_Weap_Pistol.A_Weapons_Legendary.Pistol_Torgue_5_88Fragnum")),
    ItemPool("Logan's Gun", Hint.LegendaryPistol, Item("GD_Weap_Pistol.A_Weapons_Legendary.Pistol_Hyperion_5_LogansGun")),

    ItemPool("Gwen's Other Head", Hint.UniquePistol, Item("GD_Cork_Weap_Pistol.A_Weapons_Unique.Pistol_Dahl_3_GwensOtherHead")),
    ItemPool("Globber", Hint.UniquePistol, Item("GD_Cork_Weap_Pistol.A_Weapons_Unique.Pistol_Hyperion_3_Globber")),
    ItemPool("Smasher", Hint.UniquePistol, Item("GD_Cork_Weap_Pistol.A_Weapons_Unique.Pistol_Jakobs_3_Smasher")),
    ItemPool("Cyber Eagle", Hint.UniquePistol, Item("GD_Cork_Weap_Pistol.A_Weapons_Unique.Pistol_Jakobs_CyberColt")),
    ItemPool("Probe", Hint.UniquePistol, Item("GD_Cork_Weap_Pistol.A_Weapons_Unique.Pistol_Maliwan_3_Moxxis_Probe")),

    ItemPool("Sledge's Shotty", Hint.LegendaryShotgun, Item("GD_Cork_Weap_Shotgun.A_Weapons_Legendary.SG_Bandit_5_SledgesShotgun")),
    ItemPool("Viral Marketer", Hint.LegendaryShotgun, Item("GD_Cork_Weap_Shotgun.A_Weapons_Legendary.SG_Hyperion_5_ConferenceCall")),
    ItemPool("Striker", Hint.LegendaryShotgun, Item("GD_Cork_Weap_Shotgun.A_Weapons_Legendary.SG_Jakobs_5_Striker")),
    ItemPool("Flakker", Hint.LegendaryShotgun, Item("GD_Cork_Weap_Shotgun.A_Weapons_Legendary.SG_Torgue_5_Flakker")),

    ItemPool("Boganella", Hint.UniqueShotgun, Item("GD_Cork_Weap_Shotgun.A_Weapons_Unique.SG_Bandit_3_Boganella")),
    ItemPool("Moonface", Hint.UniqueShotgun, Item("GD_Cork_Weap_Shotgun.A_Weapons_Unique.SG_Jakobs_3_Moonface")),
    ItemPool("Boomacorn", Hint.UniqueShotgun, Item("GD_Cork_Weap_Shotgun.A_Weapons_Unique.SG_Jakobs_Boomacorn")),
    ItemPool("Too Scoops", Hint.UniqueShotgun, Item("GD_Cork_Weap_Shotgun.A_Weapons_Unique.SG_Jakobs_TooScoops")),
    ItemPool("Bullpup", Hint.UniqueShotgun, Item("GD_Cork_Weap_Shotgun.A_Weapons_Unique.SG_Old_Hyperion_3_Bullpup")),
    ItemPool("Octo", Hint.UniqueShotgun, Item("GD_Cork_Weap_Shotgun.A_Weapons_Unique.SG_Tediore_3_Octo")),
    ItemPool("Jack-o'-Cannon", Hint.UniqueShotgun, Item("GD_Cork_Weap_Shotgun.A_Weapons_Unique.SG_Torgue_3_JackOCannon")),
    ItemPool("Torguemada", Hint.UniqueShotgun, Item("GD_Cork_Weap_Shotgun.A_Weapons_Unique.SG_Torgue_3_Torguemada")),
    ItemPool("Wombat", Hint.UniqueShotgun, Item("GD_Cork_Weap_Shotgun.A_Weapons_Unique.SG_Torgue_3_Wombat")),

    ItemPool("Torrent", Hint.LegendarySMG, Item("GD_Cork_Weap_SMG.A_Weapons_Legendary.SMG_Dahl_5_Torrent")),
    ItemPool("Fatale", Hint.LegendarySMG, Item("GD_Cork_Weap_SMG.A_Weapons_Legendary.SMG_Hyperion_5_Bitch")),
    ItemPool("HellFire", Hint.LegendarySMG, Item("GD_Cork_Weap_SMG.A_Weapons_Legendary.SMG_Maliwan_5_HellFire")),
    ItemPool("IVF", Hint.LegendarySMG, Item("GD_Cork_Weap_SMG.A_Weapons_Legendary.SMG_Tediore_5_IVF")),

    ItemPool("Marek's Mouth", Hint.UniqueSMG, Item("GD_Cork_Weap_SMG.A_Weapons_Unique.SMG_Bandit_3_MareksMouth")),
    ItemPool("Meat Grinder", Hint.UniqueSMG, Item("GD_Cork_Weap_SMG.A_Weapons_Unique.SMG_Bandit_3_MeatGrinder")),
    ItemPool("Black Snake", Hint.UniqueSMG, Item("GD_Cork_Weap_SMG.A_Weapons_Unique.SMG_Old_Hyperion_BlackSnake")),
    ItemPool("Fridgia", Hint.UniqueSMG, Item("GD_Weap_SMG.A_Weapons_Unique.SMG_Dahl_3_Fridgia")),
    ItemPool("Frostfire", Hint.UniqueSMG, Item("GD_Weap_SMG.A_Weapons_Unique.SMG_Maliwan_3_Frostfire")),

    ItemPool("Pitchfork", Hint.LegendarySniper, Item("GD_Cork_Weap_SniperRifles.A_Weapons_Legendary.Sniper_Dahl_5_Pitchfork")),
    ItemPool("Invader", Hint.LegendarySniper, Item("GD_Cork_Weap_SniperRifles.A_Weapons_Legendary.Sniper_Hyperion_5_Invader")),
    ItemPool("Skullmasher", Hint.LegendarySniper, Item("GD_Cork_Weap_SniperRifles.A_Weapons_Legendary.Sniper_Jakobs_5_Skullmasher")),
    ItemPool("Magma", Hint.LegendarySniper, Item("GD_Cork_Weap_SniperRifles.A_Weapons_Legendary.Sniper_Maliwan_5_Magma")),
    ItemPool("Longnail", Hint.LegendarySniper, Item("GD_Cork_Weap_SniperRifles.A_Weapons_Legendary.Sniper_Vladof_5_Longnail")),

    ItemPool("Wet Week", Hint.UniqueSniper, Item("GD_Cork_Weap_SniperRifles.A_Weapons_Unique.Sniper_Dahl_3_WetWeek")),
    ItemPool("Razorback", Hint.UniqueSniper, Item("GD_Cork_Weap_SniperRifles.A_Weapons_Unique.Sniper_Jakobs_3_Razorback")),
    ItemPool("The Machine", Hint.UniqueSniper, Item("GD_Cork_Weap_SniperRifles.A_Weapons_Unique.Sniper_Vladof_3_TheMachine")),
    ItemPool("Fremington's Edge", Hint.UniqueSniper, Item("GD_Weap_SniperRifles.A_Weapons_Unique.Sniper_Hyperion_3_FremingtonsEdge")),

    ItemPool("Boss Nova", Hint.UniqueAR, Item("GD_Cypressure_Weapons.A_Weapons_Unique.AR_Bandit_3_BossNova")),
    ItemPool("Company Man", Hint.UniqueShotgun, Item("GD_Cypressure_Weapons.A_Weapons_Unique.SG_Hyperion_3_CompanyMan")),
    ItemPool("Moonscaper", Hint.UniqueShotgun, Item("GD_Cypressure_Weapons.A_Weapons_Unique.SG_Torgue_3_Landscaper2")),
    ItemPool("Fast Talker", Hint.UniqueSMG, Item("GD_Cypressure_Weapons.A_Weapons_Unique.SMG_Bandit_3_FastTalker")),
    ItemPool("Naught", Hint.UniqueShield, Item("GD_Ma_Shields.A_Item_Unique.ItemGrade_Gear_Shield_Naught")),

    ItemPool("Bandit Assault Rifle", Hint.PurpleAR,
        Item("GD_Ma_Weapons.A_Weapons.AR_Bandit_6_Glitch", content=Tag.ClaptasticVoyage),
        fallback=Item("GD_Weap_AssaultRifle.A_Weapons.AR_Bandit_4_VeryRare"),
    ),
    ItemPool("Dahl Assault Rifle", Hint.PurpleAR,
        Item("GD_Ma_Weapons.A_Weapons.AR_Dahl_6_Glitch", content=Tag.ClaptasticVoyage),
        fallback=Item("GD_Weap_AssaultRifle.A_Weapons.AR_Dahl_4_VeryRare"),
    ),
    ItemPool("Jakobs Assault Rifle", Hint.PurpleAR,
        Item("GD_Ma_Weapons.A_Weapons.AR_Jakobs_6_Glitch", content=Tag.ClaptasticVoyage),
        fallback=Item("GD_Weap_AssaultRifle.A_Weapons.AR_Jakobs_4_VeryRare"),
    ),
    ItemPool("Torgue Assault Rifle", Hint.PurpleAR,
        Item("GD_Ma_Weapons.A_Weapons.AR_Torgue_6_Glitch", content=Tag.ClaptasticVoyage),
        fallback=Item("GD_Weap_AssaultRifle.A_Weapons.AR_Torgue_4_VeryRare"),
    ),
    ItemPool("Vladof Assault Rifle", Hint.PurpleAR,
        Item("GD_Ma_Weapons.A_Weapons.AR_Vladof_6_Glitch", content=Tag.ClaptasticVoyage),
        fallback=Item("GD_Weap_AssaultRifle.A_Weapons.AR_Vladof_4_VeryRare"),
    ),

    ItemPool("Dahl Laser", Hint.PurpleLaser,
        Item("GD_Ma_Weapons.A_Weapons.Laser_Dahl_6_Glitch", content=Tag.ClaptasticVoyage),
        fallback=Item("GD_Cork_Weap_Lasers.A_Weapons.Laser_Dahl_4_VeryRare"),
    ),
    ItemPool("Hyperion Laser", Hint.PurpleLaser,
        Item("GD_Ma_Weapons.A_Weapons.Laser_Hyperion_6_Glitch", content=Tag.ClaptasticVoyage),
        fallback=Item("GD_Cork_Weap_Lasers.A_Weapons.Laser_Hyperion_4_VeryRare"),
    ),
    ItemPool("Old Hyperion Laser", Hint.PurpleLaser,
        Item("GD_Cork_Weap_Lasers.A_Weapons.Laser_Old_Hyperion_4_VeryRare"),
    ),
    ItemPool("Maliwan Laser", Hint.PurpleLaser,
        Item("GD_Ma_Weapons.A_Weapons.Laser_Maliwan_6_Glitch", content=Tag.ClaptasticVoyage),
        fallback=Item("GD_Cork_Weap_Lasers.A_Weapons.Laser_Maliwan_4_VeryRare"),
    ),
    ItemPool("Tediore Laser", Hint.PurpleLaser,
        Item("GD_Ma_Weapons.A_Weapons.Laser_Tediore_6_Glitch", content=Tag.ClaptasticVoyage),
        fallback=Item("GD_Cork_Weap_Lasers.A_Weapons.Laser_Tediore_4_VeryRare"),
    ),

    ItemPool("Bandit Pistol", Hint.PurplePistol,
        Item("GD_Ma_Weapons.A_Weapons.Pistol_Bandit_6_Glitch", content=Tag.ClaptasticVoyage),
        fallback=Item("GD_Weap_Pistol.A_Weapons.Pistol_Bandit_4_VeryRare"),
    ),
    ItemPool("Dahl Pistol", Hint.PurplePistol,
        Item("GD_Ma_Weapons.A_Weapons.Pistol_Dahl_6_Glitch", content=Tag.ClaptasticVoyage),
        fallback=Item("GD_Weap_Pistol.A_Weapons.Pistol_Dahl_4_VeryRare"),
    ),
    ItemPool("Hyperion Pistol", Hint.PurplePistol,
        Item("GD_Ma_Weapons.A_Weapons.Pistol_Hyperion_6_Glitch", content=Tag.ClaptasticVoyage),
        fallback=Item("GD_Weap_Pistol.A_Weapons.Pistol_Hyperion_4_VeryRare"),
    ),
    ItemPool("Jakobs Pistol", Hint.PurplePistol,
        Item("GD_Ma_Weapons.A_Weapons.Pistol_Jakobs_6_Glitch", content=Tag.ClaptasticVoyage),
        fallback=Item("GD_Weap_Pistol.A_Weapons.Pistol_Jakobs_4_VeryRare"),
    ),
    ItemPool("Maliwan Pistol", Hint.PurplePistol,
        Item("GD_Ma_Weapons.A_Weapons.Pistol_Maliwan_6_Glitch", content=Tag.ClaptasticVoyage),
        fallback=Item("GD_Weap_Pistol.A_Weapons.Pistol_Maliwan_4_VeryRare"),
    ),
    ItemPool("Old Hyperion Pistol", Hint.PurplePistol,
        Item("GD_Ma_Weapons.A_Weapons.Pistol_Old_Hyperion_6_Glitch", content=Tag.ClaptasticVoyage),
        fallback=Item("GD_Weap_Pistol.A_Weapons.Pistol_Old_Hyperion_4_VeryRare"),
    ),
    ItemPool("Tediore Pistol", Hint.PurplePistol,
        Item("GD_Ma_Weapons.A_Weapons.Pistol_Tediore_6_Glitch", content=Tag.ClaptasticVoyage),
        fallback=Item("GD_Weap_Pistol.A_Weapons.Pistol_Tediore_4_VeryRare"),
    ),
    ItemPool("Torgue Pistol", Hint.PurplePistol,
        Item("GD_Ma_Weapons.A_Weapons.Pistol_Torgue_6_Glitch", content=Tag.ClaptasticVoyage),
        fallback=Item("GD_Weap_Pistol.A_Weapons.Pistol_Torgue_4_VeryRare"),
    ),
    ItemPool("Vladof Pistol", Hint.PurplePistol,
        Item("GD_Ma_Weapons.A_Weapons.Pistol_Vladof_6_Glitch", content=Tag.ClaptasticVoyage),
        fallback=Item("GD_Weap_Pistol.A_Weapons.Pistol_Vladof_4_VeryRare"),
    ),

    ItemPool("Bandit Rocket Launcher", Hint.PurpleLauncher,
        Item("GD_Ma_Weapons.A_Weapons.RL_Bandit_6_Glitch", content=Tag.ClaptasticVoyage),
        fallback=Item("GD_Weap_Launchers.A_Weapons.RL_Bandit_4_VeryRare"),
    ),
    ItemPool("Maliwan Rocket Launcher", Hint.PurpleLauncher,
        Item("GD_Ma_Weapons.A_Weapons.RL_Maliwan_6_Glitch", content=Tag.ClaptasticVoyage),
        fallback=Item("GD_Weap_Launchers.A_Weapons.RL_Maliwan_4_VeryRare"),
    ),
    ItemPool("Tediore Rocket Launcher", Hint.PurpleLauncher,
        Item("GD_Ma_Weapons.A_Weapons.RL_Tediore_6_Glitch", content=Tag.ClaptasticVoyage),
        fallback=Item("GD_Weap_Launchers.A_Weapons.RL_Tediore_4_VeryRare"),
    ),
    ItemPool("Torgue Rocket Launcher", Hint.PurpleLauncher,
        Item("GD_Ma_Weapons.A_Weapons.RL_Torgue_6_Glitch", content=Tag.ClaptasticVoyage),
        fallback=Item("GD_Weap_Launchers.A_Weapons.RL_Torgue_4_VeryRare"),
    ),
    ItemPool("Vladof Rocket Launcher", Hint.PurpleLauncher,
        Item("GD_Ma_Weapons.A_Weapons.RL_Vladof_6_Glitch", content=Tag.ClaptasticVoyage),
        fallback=Item("GD_Weap_Launchers.A_Weapons.RL_Vladof_4_VeryRare"),
    ),

    ItemPool("Bandit Shotgun", Hint.PurpleShotgun,
        Item("GD_Ma_Weapons.A_Weapons.SG_Bandit_6_Glitch", content=Tag.ClaptasticVoyage),
        fallback=Item("GD_Weap_Shotgun.A_Weapons.SG_Bandit_4_VeryRare"),
    ),
    ItemPool("Hyperion Shotgun", Hint.PurpleShotgun,
        Item("GD_Ma_Weapons.A_Weapons.SG_Hyperion_6_Glitch", content=Tag.ClaptasticVoyage),
        fallback=Item("GD_Weap_Shotgun.A_Weapons.SG_Hyperion_4_VeryRare"),
    ),
    ItemPool("Jakobs Shotgun", Hint.PurpleShotgun,
        Item("GD_Ma_Weapons.A_Weapons.SG_Jakobs_6_Glitch", content=Tag.ClaptasticVoyage),
        fallback=Item("GD_Weap_Shotgun.A_Weapons.SG_Jakobs_4_VeryRare"),
    ),
    ItemPool("Old Hyperion Shotgun", Hint.PurpleShotgun,
        Item("GD_Ma_Weapons.A_Weapons.SG_Old_Hyperion_6_Glitch", content=Tag.ClaptasticVoyage),
        fallback=Item("GD_Weap_Shotgun.A_Weapons.SG_Old_Hyperion_4_VeryRare"),
    ),
    ItemPool("Tediore Shotgun", Hint.PurpleShotgun,
        Item("GD_Ma_Weapons.A_Weapons.SG_Tediore_6_Glitch", content=Tag.ClaptasticVoyage),
        fallback=Item("GD_Weap_Shotgun.A_Weapons.SG_Tediore_4_VeryRare"),
    ),
    ItemPool("Torgue Shotgun", Hint.PurpleShotgun,
        Item("GD_Ma_Weapons.A_Weapons.SG_Torgue_6_Glitch", content=Tag.ClaptasticVoyage),
        fallback=Item("GD_Weap_Shotgun.A_Weapons.SG_Torgue_4_VeryRare"),
    ),

    ItemPool("Bandit SMG", Hint.PurpleSMG,
        Item("GD_Ma_Weapons.A_Weapons.SMG_Bandit_6_Glitch", content=Tag.ClaptasticVoyage),
        fallback=Item("GD_Weap_SMG.A_Weapons.SMG_Bandit_4_VeryRare"),
    ),
    ItemPool("Dahl SMG", Hint.PurpleSMG,
        Item("GD_Ma_Weapons.A_Weapons.SMG_Dahl_6_Glitch", content=Tag.ClaptasticVoyage),
        fallback=Item("GD_Weap_SMG.A_Weapons.SMG_Dahl_4_VeryRare"),
    ),
    ItemPool("Hyperion SMG", Hint.PurpleSMG,
        Item("GD_Ma_Weapons.A_Weapons.SMG_Hyperion_6_Glitch", content=Tag.ClaptasticVoyage),
        fallback=Item("GD_Weap_SMG.A_Weapons.SMG_Hyperion_4_VeryRare"),
    ),
    ItemPool("Old Hyperion SMG", Hint.PurpleSMG,
        Item("GD_Ma_Weapons.A_Weapons.SMG_Old_Hyperion_6_Glitch", content=Tag.ClaptasticVoyage),
        fallback=Item("GD_Weap_SMG.A_Weapons.SMG_Old_Hyperion_4_VeryRare"),
    ),
    ItemPool("Maliwan SMG", Hint.PurpleSMG,
        Item("GD_Ma_Weapons.A_Weapons.SMG_Maliwan_6_Glitch", content=Tag.ClaptasticVoyage),
        fallback=Item("GD_Weap_SMG.A_Weapons.SMG_Maliwan_4_VeryRare"),
    ),
    ItemPool("Tediore SMG", Hint.PurpleSMG,
        Item("GD_Ma_Weapons.A_Weapons.SMG_Tediore_6_Glitch", content=Tag.ClaptasticVoyage),
        fallback=Item("GD_Weap_SMG.A_Weapons.SMG_Tediore_4_VeryRare"),
    ),

    ItemPool("Dahl Sniper", Hint.PurpleSniper,
        Item("GD_Ma_Weapons.A_Weapons.Sniper_Dahl_6_Glitch", content=Tag.ClaptasticVoyage),
        fallback=Item("GD_Weap_SniperRifles.A_Weapons.Sniper_Dahl_4_VeryRare"),
    ),
    ItemPool("Hyperion Sniper", Hint.PurpleSniper,
        Item("GD_Ma_Weapons.A_Weapons.Sniper_Hyperion_6_Glitch", content=Tag.ClaptasticVoyage),
        fallback=Item("GD_Weap_SniperRifles.A_Weapons.Sniper_Hyperion_4_VeryRare"),
    ),
    ItemPool("Old Hyperion Sniper", Hint.PurpleSniper,
        Item("GD_Weap_SniperRifles.A_Weapons.Sniper_Old_Hyperion_4_VeryRare"),
    ),
    ItemPool("Jakobs Sniper", Hint.PurpleSniper,
        Item("GD_Ma_Weapons.A_Weapons.Sniper_Jakobs_6_Glitch", content=Tag.ClaptasticVoyage),
        fallback=Item("GD_Weap_SniperRifles.A_Weapons.Sniper_Jakobs_4_VeryRare"),
    ),
    ItemPool("Maliwan Sniper", Hint.PurpleSniper,
        Item("GD_Ma_Weapons.A_Weapons.Sniper_Maliwan_6_Glitch", content=Tag.ClaptasticVoyage),
        fallback=Item("GD_Weap_SniperRifles.A_Weapons.Sniper_Maliwan_4_VeryRare"),
    ),
    ItemPool("Vladof Sniper", Hint.PurpleSniper,
        Item("GD_Ma_Weapons.A_Weapons.Sniper_Vladof_6_Glitch", content=Tag.ClaptasticVoyage),
        fallback=Item("GD_Weap_SniperRifles.A_Weapons.Sniper_Vladof_4_VeryRare"),
    ),

    ItemPool("Fire Burst / Tesla / Corrosive Cloud / Cryo", Hint.PurpleGrenade, Item("GD_GrenadeMods.A_Item.GM_AreaEffect_4_VeryRare")),
    ItemPool("Bouncing Betty", Hint.PurpleGrenade, BanditGrenade("GD_GrenadeMods.A_Item.GM_BouncingBetty_4_VeryRare", 1)),
    ItemPool("Sheila", Hint.PurpleGrenade, BanditGrenade("GD_GrenadeMods.A_Item.GM_BouncingBetty_4_VeryRare", 0)),
    ItemPool("MIRV", Hint.PurpleGrenade, BanditGrenade("GD_GrenadeMods.A_Item.GM_Mirv_4_VeryRare", 1)),
    ItemPool("Merv", Hint.PurpleGrenade, BanditGrenade("GD_GrenadeMods.A_Item.GM_Mirv_4_VeryRare", 0)),
    ItemPool("Grenade", Hint.PurpleGrenade, BanditGrenade("GD_GrenadeMods.A_Item.GM_Standard_4_VeryRare", 1)),
    ItemPool("Gr'nade", Hint.PurpleGrenade, BanditGrenade("GD_GrenadeMods.A_Item.GM_Standard_4_VeryRare", 0)),
    ItemPool("Singularity", Hint.PurpleGrenade, Item("GD_GrenadeMods.A_Item.GM_Singularity_4_VeryRare")),
    ItemPool("Transfusion", Hint.PurpleGrenade, Item("GD_GrenadeMods.A_Item.GM_Transfusion_4_VeryRare")),

    ItemPool("Kiss of Death", Hint.UniqueGrenade, Item("GD_Cork_GrenadeMods.A_Item_Custom.GM_KissOfDeath")),
    ItemPool("Baby Boomer", Hint.UniqueGrenade, Item("GD_GrenadeMods.A_Item_Custom.GM_BabyBoomer")),
    ItemPool("Contraband Sky Rocket", Hint.UniqueGrenade, Item("GD_GrenadeMods.A_Item_Custom.GM_SkyRocket")),
    ItemPool("Snowball", Hint.UniqueGrenade, Item("GD_GrenadeMods.A_Item_Custom.GM_Snowball")),

    ItemPool("Bonus Package", Hint.LegendaryGrenade, Item("GD_Cork_GrenadeMods.A_Item_Legendary.GM_BonusPackage")),
    ItemPool("Bouncing Bazza", Hint.LegendaryGrenade, Item("GD_GrenadeMods.A_Item_Legendary.GM_BouncingBonny")),
    ItemPool("Fire Bee", Hint.LegendaryGrenade, Item("GD_GrenadeMods.A_Item_Legendary.GM_FireBee")),
    ItemPool("Four Seasons", Hint.LegendaryGrenade, Item("GD_GrenadeMods.A_Item_Legendary.GM_FourSeasons")),
    ItemPool("Leech", Hint.LegendaryGrenade, Item("GD_GrenadeMods.A_Item_Legendary.GM_Leech")),
    ItemPool("Nasty Surprise", Hint.LegendaryGrenade, Item("GD_GrenadeMods.A_Item_Legendary.GM_NastySurprise")),
    ItemPool("Pandemic", Hint.LegendaryGrenade, Item("GD_GrenadeMods.A_Item_Legendary.GM_Pandemic")),
    ItemPool("Quasar", Hint.LegendaryGrenade, Item("GD_Cork_GrenadeMods.A_Item_Legendary.GM_Quasar")),
    ItemPool("Rolling Thunder", Hint.LegendaryGrenade, Item("GD_GrenadeMods.A_Item_Legendary.GM_RollingThunder")),
    ItemPool("Storm Front", Hint.LegendaryGrenade, Item("GD_GrenadeMods.A_Item_Legendary.GM_StormFront")),

    ItemPool("Shield", Hint.PurpleShield, Item("GD_ItemGrades.Shields.ItemGrade_Gear_Shield_Standard_04_VeryRare")),
    ItemPool("Absorb Shield", Hint.PurpleShield, Item("GD_ItemGrades.Shields.ItemGrade_Gear_Shield_Absorption_04_VeryRare")),
    ItemPool("Adaptive Shield", Hint.PurpleShield, Item("GD_ItemGrades.Shields.ItemGrade_Gear_Shield_Chimera_04_VeryRare")),
    ItemPool("Amplify Shield", Hint.PurpleShield, Item("GD_ItemGrades.Shields.ItemGrade_Gear_Shield_Impact_04_VeryRare")),
    ItemPool("Booster Shield", Hint.PurpleShield, Item("GD_ItemGrades.Shields.ItemGrade_Gear_Shield_Booster_04_VeryRare")),
    ItemPool("Maylay Shield", Hint.PurpleShield, Item("GD_ItemGrades.Shields.ItemGrade_Gear_Shield_Roid_04_VeryRare")),
    ItemPool("Nova Shield", Hint.PurpleShield,
        Item("GD_Cork_ItemGrades.Shields.ItemGrade_Gear_Shield_Nova_Ice_04_VeryRare"),
        Item("GD_ItemGrades.Shields.ItemGrade_Gear_Shield_Nova_Acid_04_VeryRare"),
        Item("GD_ItemGrades.Shields.ItemGrade_Gear_Shield_Nova_Explosive_04_VeryRare"),
        Item("GD_ItemGrades.Shields.ItemGrade_Gear_Shield_Nova_Fire_04_VeryRare"),
        Item("GD_ItemGrades.Shields.ItemGrade_Gear_Shield_Nova_Shock_04_VeryRare"),
    ),
    ItemPool("Spike Shield", Hint.PurpleShield,
        Item("GD_ItemGrades.Shields.ItemGrade_Gear_Shield_Spike_Acid_04_VeryRare"),
        Item("GD_ItemGrades.Shields.ItemGrade_Gear_Shield_Spike_Explosive_04_VeryRare"),
        Item("GD_ItemGrades.Shields.ItemGrade_Gear_Shield_Spike_Fire_04_VeryRare"),
        Item("GD_ItemGrades.Shields.ItemGrade_Gear_Shield_Spike_Shock_04_VeryRare"),
        Item("GD_Cork_ItemGrades.Shields.ItemGrade_Gear_Shield_Spike_Ice_05_Legendary"),
    ),
    ItemPool("Turtle Shield", Hint.PurpleShield, Item("GD_ItemGrades.Shields.ItemGrade_Gear_Shield_Juggernaut_04_VeryRare")),

    ItemPool("Avalanche", Hint.LegendaryShield, Item("GD_ItemGrades.Shields.ItemGrade_Gear_Shield_Roid_Avalanche")),
    ItemPool("Bigg Thumppr", Hint.LegendaryShield, Item("GD_ItemGrades.Shields.ItemGrade_Gear_Shield_Roid_05_Legendary")),
    ItemPool("Black Hole", Hint.LegendaryShield, Item("GD_ItemGrades.Shields.ItemGrade_Gear_Shield_Nova_Singularity")),
    ItemPool("Fabled Tortoise", Hint.LegendaryShield, Item("GD_ItemGrades.Shields.ItemGrade_Gear_Shield_Juggernaut_05_Legendary")),
    ItemPool("Kala", Hint.LegendaryShield, Item("GD_ItemGrades.Shields.ItemGrade_Gear_Shield_Absorption_05_LegendaryShock")),
    ItemPool("Prismatic Bulwark", Hint.LegendaryShield, Item("GD_ItemGrades.Shields.ItemGrade_Gear_Shield_Absorption_PrismaticBulwark")),
    ItemPool("Reogenator", Hint.LegendaryShield, Item("GD_ItemGrades.Shields.ItemGrade_Gear_Shield_Chimera_05_Legendary")),
    ItemPool("The Cradle", Hint.LegendaryShield, Item("GD_ItemGrades.Shields.ItemGrade_Gear_Shield_Standard_05_Legendary")),
    ItemPool("The Sham", Hint.LegendaryShield, Item("GD_ItemGrades.Shields.ItemGrade_Gear_Shield_Absorption_05_LegendaryNormal")),
    ItemPool("The Shooting Star", Hint.LegendaryShield, Item("GD_ItemGrades.Shields.ItemGrade_Gear_Shield_Roid_ShootingStar")),
    ItemPool("Whisky Tango Foxtrot", Hint.LegendaryShield, Item("GD_ItemGrades.Shields.ItemGrade_Gear_Shield_Booster_05_Legendary")),

    ItemPool("Asteroid Belt", Hint.UniqueShield, Item("GD_ItemGrades.Shields.ItemGrade_Gear_Shield_Booster_AsteroidBelt")),
    ItemPool("Deadly Bloom", Hint.UniqueShield, Item("GD_ItemGrades.Shields.ItemGrade_Gear_Shield_Nova_Explosive_DeadlyBloom")),
    ItemPool("Haymaker", Hint.UniqueShield, Item("GD_ItemGrades.Shields.ItemGrade_Gear_Shield_Chimera_Haymaker")),
    ItemPool("Miss Moxxi's Slammer", Hint.UniqueShield, Item("GD_ItemGrades.Shields.ItemGrade_Gear_Shield_Booster_MoxxisSlammer")),
    ItemPool("Rapid Release", Hint.UniqueShield, Item("GD_Cork_Shields.A_Item_Custom.ItemGrade_Shield_RapidRelease")),
    ItemPool("Sunshine", Hint.UniqueShield, Item("GD_ItemGrades.Shields.ItemGrade_Gear_Shield_Nova_Starburst")),
    ItemPool("Supernova", Hint.UniqueShield, Item("GD_ItemGrades.Shields.ItemGrade_Gear_Shield_Nova_Supernova")),

    ItemPool("Acrobat Oz Kit", Hint.PurpleOz, Item("GD_MoonItems.BalanceDefinitions.A_Acrobat_04_VeryRare")),
    ItemPool("Clear Skies Oz Kit", Hint.PurpleOz, Item("GD_MoonItems.BalanceDefinitions.A_AntiAir_04_VeryRare")),
    ItemPool("Bomber Oz Kit", Hint.PurpleOz, Item("GD_MoonItems.BalanceDefinitions.A_Bomber_04_VeryRare")),
    ItemPool("Hyperventilator Oz Kit", Hint.PurpleOz, Item("GD_MoonItems.BalanceDefinitions.A_Hyperventilator_04_VeryRare")),
    ItemPool("Juggernaut Oz Kit", Hint.PurpleOz, Item("GD_MoonItems.BalanceDefinitions.A_Juggernaut_04_VeryRare")),
    ItemPool("Precision Strike Oz Kit", Hint.PurpleOz, Item("GD_MoonItems.BalanceDefinitions.A_PrecisionStrike_04_VeryRare")),
    ItemPool("Strafing Run Oz Kit", Hint.PurpleOz, Item("GD_MoonItems.BalanceDefinitions.A_StrafingRun_04_VeryRare")),
    ItemPool("Tranquility Oz Kit", Hint.PurpleOz, Item("GD_MoonItems.BalanceDefinitions.A_Tranquility_04_VeryRare")),

    ItemPool("Shotgun Duality Oz Kit", Hint.PurpleOz,
        Item("GD_MoonItems.BalanceDefinitions.A_DualityA_04_VeryRare"), # Shotgun & Sniper
        Item("GD_MoonItems.BalanceDefinitions.A_DualityH_04_VeryRare"), # Shotgun & Assault Rifle
        Item("GD_MoonItems.BalanceDefinitions.A_DualityI_04_VeryRare"), # Launcher & Shotgun
    ),
    ItemPool("Sniper Duality Oz Kit", Hint.PurpleOz,
        Item("GD_MoonItems.BalanceDefinitions.A_DualityA_04_VeryRare"), # Shotgun & Sniper
        Item("GD_MoonItems.BalanceDefinitions.A_DualityJ_04_VeryRare"), # Laser & Sniper
    ),
    ItemPool("Laser Duality Oz Kit", Hint.PurpleOz,
        Item("GD_MoonItems.BalanceDefinitions.A_DualityB_04_VeryRare"), # Laser & Assault Rifle
        Item("GD_MoonItems.BalanceDefinitions.A_DualityE_04_VeryRare"), # Launcher & Laser
        Item("GD_MoonItems.BalanceDefinitions.A_DualityF_04_VeryRare"), # Laser & Pistol
        Item("GD_MoonItems.BalanceDefinitions.A_DualityG_04_VeryRare"), # SMG & Laser
        Item("GD_MoonItems.BalanceDefinitions.A_DualityJ_04_VeryRare"), # Laser & Sniper
    ),
    ItemPool("Assault Rifle Duality Oz Kit", Hint.PurpleOz,
        Item("GD_MoonItems.BalanceDefinitions.A_DualityB_04_VeryRare"), # Laser & Assault Rifle
        Item("GD_MoonItems.BalanceDefinitions.A_DualityH_04_VeryRare"), # Shotgun & Assault Rifle
    ),
    ItemPool("Pistol Duality Oz Kit", Hint.PurpleOz,
        Item("GD_MoonItems.BalanceDefinitions.A_DualityC_04_VeryRare"), # Pistol & SMG
        Item("GD_MoonItems.BalanceDefinitions.A_DualityF_04_VeryRare"), # Laser & Pistol
    ),
    ItemPool("SMG Duality Oz Kit", Hint.PurpleOz,
        Item("GD_MoonItems.BalanceDefinitions.A_DualityC_04_VeryRare"), # Pistol & SMG
        Item("GD_MoonItems.BalanceDefinitions.A_DualityG_04_VeryRare"), # SMG & Laser
        Item("GD_MoonItems.BalanceDefinitions.A_DualityD_04_VeryRare"), # SMG & Launcher
    ),
    ItemPool("Launcher Duality Oz Kit", Hint.PurpleOz,
        Item("GD_MoonItems.BalanceDefinitions.A_DualityE_04_VeryRare"), # Launcher & Laser
        Item("GD_MoonItems.BalanceDefinitions.A_DualityI_04_VeryRare"), # Launcher & Shotgun
        Item("GD_MoonItems.BalanceDefinitions.A_DualityD_04_VeryRare"), # SMG & Launcher
    ),
    ItemPool("Elemental Duality Oz Kit", Hint.PurpleOz,
        Item("GD_MoonItems.BalanceDefinitions.A_TwoFaceA_04_VeryRare"), # Corrosive
        Item("GD_MoonItems.BalanceDefinitions.A_TwoFaceB_04_VeryRare"), # Incendiary
        Item("GD_MoonItems.BalanceDefinitions.A_TwoFaceC_04_VeryRare"), # Shock
        Item("GD_MoonItems.BalanceDefinitions.A_TwoFaceD_04_VeryRare"), # Explosive
        Item("GD_MoonItems.BalanceDefinitions.A_TwoFaceF_04_VeryRare"), # Cryo
    ),

    ItemPool("Melee Duality Oz Kit", Hint.PurpleOz, Item("GD_MoonItems.BalanceDefinitions.A_TwoFaceG_04_VeryRare")),

    ItemPool("3DD1.E", Hint.LegendaryOz, Item("GD_MoonItems.A_Item_Unique.A_Astrotech")),
    ItemPool("Ack Ack", Hint.LegendaryOz, Item("GD_MoonItems.A_Item_Unique.A_AckAck")),
    ItemPool("Moonlight Saga", Hint.LegendaryOz, Item("GD_MoonItems.A_Item_Unique.A_MoonlightSaga")),
    ItemPool("Oxidizer", Hint.LegendaryOz, Item("GD_MoonItems.A_Item_Unique.A_Oxidizer")),
    ItemPool("Support Relay", Hint.LegendaryOz, Item("GD_MoonItems.A_Item_Unique.A_SupportRelay")),

    ItemPool("Cathartic Oz Kit", Hint.UniqueOz, Item("GD_MoonItems.A_Item_Unique.A_Poopdeck")),
    ItemPool("Freedom Oz Kit", Hint.UniqueOz, Item("GD_MoonItems.A_Item_Unique.A_Freedom")),
    ItemPool("Invigoration Oz Kit", Hint.UniqueOz, Item("GD_MoonItems.A_Item_Unique.A_Invigoration")),
    ItemPool("Perdy Lights", Hint.UniqueOz, Item("GD_Pet_MoonItems.A_Item_Unique.A_AntiAir_PerdyLights")),
    ItemPool("Springs' Oz Kit", Hint.UniqueOz, Item("GD_MoonItems.A_Item_Unique.A_Springs")),
    ItemPool("Systems Purge", Hint.UniqueOz, Item("GD_MoonItems.A_Item_Unique.A_SystemsPurge")),

    ItemPool("Fusillade", Hint.LegendaryAR, Item("GD_Ma_Weapons.A_Weapons_Legendary.AR_Bandit_5_Fusillade", content=Tag.ClaptasticVoyage)),
    ItemPool("Luck Cannon", Hint.LegendaryPistol, Item("GD_Ma_Weapons.A_Weapons_Legendary.Pistol_Jakobs_5_LuckCannon", content=Tag.ClaptasticVoyage)),
    ItemPool("Proletarian Revolution", Hint.LegendaryPistol, Item("GD_Ma_Weapons.A_Weapons_Legendary.Pistol_Vladof_5_Expander", content=Tag.ClaptasticVoyage)),
    ItemPool("Longest Yard", Hint.LegendaryLaser, Item("GD_Ma_Weapons.A_Weapons_Legendary.Laser_Hyperion_5_LongestYard", content=Tag.ClaptasticVoyage)),
    ItemPool("Absolute Zero", Hint.LegendaryLaser, Item("GD_Ma_Weapons.A_Weapons_Legendary.Laser_Maliwan_5_FusionBeam", content=Tag.ClaptasticVoyage)),
    ItemPool("Thunderfire", Hint.LegendaryLaser, Item("GD_Ma_Weapons.A_Weapons_Legendary.Laser_Maliwan_5_Thunderfire", content=Tag.ClaptasticVoyage)),
    ItemPool("Laser Disker", Hint.LegendaryLaser, Item("GD_Ma_Weapons.A_Weapons_Legendary.Laser_Tediore_5_LaserDisker", content=Tag.ClaptasticVoyage)),
    ItemPool("Tannis' Laser of Enlightenment", Hint.UniqueLaser, Item("GD_Ma_Weapons.A_Weapons_Unique.Laser_Maliwan_3_Enlightenment", content=Tag.ClaptasticVoyage)),
    ItemPool("MINAC's Atonement", Hint.UniqueLaser, Item("GD_Ma_Weapons.A_Weapons_Unique.Laser_Maliwan_3_Minac", content=Tag.ClaptasticVoyage)),
    ItemPool("Kaneda's Laser", Hint.UniqueLauncher, Item("GD_Ma_Weapons.A_Weapons_Legendary.RL_Tediore_5_KanedasLaser", content=Tag.ClaptasticVoyage)),
    ItemPool("Flayer", Hint.LegendaryShotgun, Item("GD_Ma_Weapons.A_Weapons_Legendary.SG_Jakobs_5_Flayer", content=Tag.ClaptasticVoyage)),
    ItemPool("Cheat Code", Hint.LegendarySMG, Item("GD_Ma_Weapons.A_Weapons_Legendary.SMG_Hyperion_5_CheatCode", content=Tag.ClaptasticVoyage)),
    ItemPool("Omni-Cannon", Hint.LegendarySniper, Item("GD_Ma_Weapons.A_Weapons_Legendary.Sniper_Old_Hyperion_5_OmniCannon", content=Tag.ClaptasticVoyage)),
    ItemPool("/He4rtf;ull Spl0Dge..r", Hint.UniqueSMG, Item("GD_Ma_Weapons.A_Weapons_Unique.Laser_Dahl_6_Glitch_HeartfullSplodger", content=Tag.ClaptasticVoyage)),
    ItemPool("Party Popper", Hint.UniquePistol, Item("GD_Ma_Weapons.A_Weapons_Unique.Pistol_Bandit_3_PartyPopper", content=Tag.ClaptasticVoyage)),
    ItemPool("Hard Reboot", Hint.UniquePistol, Item("GD_Ma_Weapons.A_Weapons_Unique.Pistol_Maliwan_3_HardReboot", content=Tag.ClaptasticVoyage)),
    ItemPool("%Cu+ie^_^ki||er", Hint.UniqueSMG, Item("GD_Ma_Weapons.A_Weapons_Unique.SMG_Bandit_6_Glitch_CutieKiller", content=Tag.ClaptasticVoyage)),

    ItemPool("Meganade", Hint.LegendaryGrenade, Item("GD_Ma_GrenadeMods.A_Item_Legendary.GM_Meganade", content=Tag.ClaptasticVoyage)),
    ItemPool("Data Scrubber", Hint.UniqueGrenade, Item("GD_Ma_GrenadeMods.A_Item_Unique.GM_DataScrubber", content=Tag.ClaptasticVoyage)),
    ItemPool("M0RQ", Hint.LegendaryShield, Item("GD_Ma_Shields.A_Item_Legendary.ItemGrade_Gear_Shield_Chimera_05_M0RQ", content=Tag.ClaptasticVoyage)),
    ItemPool("Rerouter", Hint.LegendaryShield, Item("GD_Ma_Shields.A_Item_Legendary.ItemGrade_Gear_Shield_Impact_05_Rerouter", content=Tag.ClaptasticVoyage)),
    ItemPool("Shield of Ages", Hint.UniqueShield, Item("GD_Ma_Shields.A_Item_Unique.ItemGrade_Gear_Shield_Juggernaut_03_ShieldOfAges", content=Tag.ClaptasticVoyage)),

    ItemPool("Cry Baby", Hint.UniqueAR, MultiBarrelWeapon("GD_Petunia_Weapons.AssaultRifles.AR_Bandit_3_CryBaby", 0, content=Tag.Holodome)),
    ItemPool("Wiggly Cry Baby", Hint.UniqueAR, MultiBarrelWeapon("GD_Petunia_Weapons.AssaultRifles.AR_Bandit_3_CryBaby", 1, content=Tag.Holodome)),

    ItemPool("Berrigan", Hint.UniqueLauncher, Item("GD_Petunia_Weapons.Launchers.RL_Vladof_5_Menace", content=Tag.Holodome)),
    ItemPool("T4s-R", Hint.UniquePistol, Item("GD_Petunia_Weapons.Pistols.Pistol_Hyperion_3_T4sr", content=Tag.Holodome)),
    ItemPool("Party Line", Hint.UniqueShotgun, Item("GD_Petunia_Weapons.Shotguns.SG_Tediore_3_PartyLine", content=Tag.Holodome)),
    ItemPool("Boxxy Gunn", Hint.UniqueSMG, Item("GD_Petunia_Weapons.SMGs.SMG_Tediore_3_Boxxy", content=Tag.Holodome)),
    ItemPool("Plunkett", Hint.UniqueSniper, Item("GD_Petunia_Weapons.Snipers.Sniper_Jakobs_3_Plunkett", content=Tag.Holodome)),
)
