from . import Tag
from ..seed import SeedEntry

Tags = (
    Tag.BaseGame
    | Tag.Holodome
    | Tag.ClaptasticVoyage
    | Tag.ShockDrop
    | Tag.TalesLoyalty
    | Tag.ShortMission
    | Tag.LongMission
    | Tag.VeryLongMission
    | Tag.Slaughter
    | Tag.VehicleMission
    | Tag.UniqueEnemy
    | Tag.SlowEnemy
    | Tag.RareEnemy
    | Tag.VeryRareEnemy
    | Tag.MobFarm
    | Tag.RaidEnemy
    | Tag.MissionEnemy
    | Tag.EvolvedEnemy
    | Tag.Miscellaneous
    | Tag.DuplicateItems
    | Tag.EnableHints
)

# fmt: off

Items = (
    SeedEntry("Blue Bloodthirster / Blaster / Cowgirl / Brotrap / CEO / Big Game Hunter", Tag.BaseGame),
    SeedEntry("Blue Cannoness / Obliterator / Crapshooter / Factory Second / Entrepreneur / Sport Hunter", Tag.BaseGame),
    SeedEntry("Blue Defender / Equalizer / Desperado / Sapper / Hero / Crème de la Crème", Tag.BaseGame),
    SeedEntry("Blue Dominator / Fighter / The Kid / Madtrap / Paragon / Privileged", Tag.BaseGame),
    SeedEntry("Blue Dragon / Golem / Bounty Hunter / Overclocker / VIP / Blue Blood", Tag.BaseGame),
    SeedEntry("Blue Femme Fatale / Howitzer / Rustler / Piñata / Antagonist / Gentry", Tag.BaseGame),
    SeedEntry("Blue Gladiatrix / Mauler / The Lone Star / Loose Cannon / Role Model / Lady", Tag.BaseGame),
    SeedEntry("Blue Protector / Mech / Sheriff / Roboninja / Protagonist / Master", Tag.BaseGame),
    SeedEntry("Blue Storm / Scorcher / Six-Shooter / Short Circuit / Best Man / Mistress", Tag.BaseGame),
    SeedEntry("Blue Hologram / Projector / Illusion / Glitch / Projection / High Definition", Tag.Holodome),
    SeedEntry("Purple Bloodthirster / Blaster / Cowgirl / Brotrap / CEO / Big Game Hunter", Tag.BaseGame),
    SeedEntry("Purple Cannoness / Obliterator / Crapshooter / Factory Second / Entrepreneur / Sport Hunter", Tag.BaseGame),
    SeedEntry("Purple Defender / Equalizer / Desperado / Sapper / Hero / Crème de la Crème", Tag.BaseGame),
    SeedEntry("Purple Dominator / Fighter / The Kid / Madtrap / Paragon / Privileged", Tag.BaseGame),
    SeedEntry("Purple Dragon / Golem / Bounty Hunter / Overclocker / VIP / Blue Blood", Tag.BaseGame),
    SeedEntry("Purple Femme Fatale / Howitzer / Rustler / Piñata / Antagonist / Gentry", Tag.BaseGame),
    SeedEntry("Purple Gladiatrix / Mauler / The Lone Star / Loose Cannon / Role Model / Lady", Tag.BaseGame),
    SeedEntry("Purple Protector / Mech / Sheriff / Roboninja / Protagonist / Master", Tag.BaseGame),
    SeedEntry("Purple Storm / Scorcher / Six-Shooter / Short Circuit / Best Man / Mistress", Tag.BaseGame),
    SeedEntry("Purple Hologram / Projector / Illusion / Glitch / Projection / High Definition", Tag.Holodome),
    SeedEntry("Celestial Gladiator / Enforcer / Lawbringer / Fragtrap / Doppelganger / Baroness", Tag.BaseGame),
    SeedEntry("Eridian Vanquisher", Tag.BaseGame),
    SeedEntry("Chronicler Of Elpis", Tag.Holodome),
    SeedEntry("Major Tom", Tag.BaseGame),
    SeedEntry("Hammer Buster II", Tag.BaseGame),
    SeedEntry("KerBoom", Tag.BaseGame),
    SeedEntry("Shredifier", Tag.BaseGame),
    SeedEntry("Wallop", Tag.BaseGame),
    SeedEntry("Hail", Tag.BaseGame),
    SeedEntry("Ice Scream", Tag.BaseGame),
    SeedEntry("Ol' Painful", Tag.BaseGame),
    SeedEntry("Cat o' Nine Tails", Tag.BaseGame),
    SeedEntry("The ZX-1", Tag.BaseGame),
    SeedEntry("Excalibastard", Tag.BaseGame),
    SeedEntry("Min Min Lighter", Tag.BaseGame),
    SeedEntry("Firestarta", Tag.BaseGame),
    SeedEntry("Mining Laser", Tag.BaseGame),
    SeedEntry("Lazlo's Freezeasy", Tag.BaseGame),
    SeedEntry("Vibra-Pulse", Tag.BaseGame),
    SeedEntry("E-GUN", Tag.BaseGame),
    SeedEntry("Ol' Rosie", Tag.BaseGame),
    SeedEntry("Toby's Bright Spadroon", Tag.BaseGame),
    SeedEntry("Vandergraffen", Tag.BaseGame),
    SeedEntry("Badaboom", Tag.BaseGame),
    SeedEntry("Thingy", Tag.BaseGame),
    SeedEntry("Cryophobia", Tag.BaseGame),
    SeedEntry("Nukem", Tag.BaseGame),
    SeedEntry("Mongol", Tag.BaseGame),
    SeedEntry("Volt Thrower", Tag.BaseGame),
    SeedEntry("Zim", Tag.BaseGame),
    SeedEntry("Blowfly", Tag.BaseGame),
    SeedEntry("Maggie", Tag.BaseGame),
    SeedEntry("Shooterang", Tag.BaseGame),
    SeedEntry("88 Fragnum", Tag.BaseGame),
    SeedEntry("Logan's Gun", Tag.BaseGame),
    SeedEntry("Gwen's Other Head", Tag.BaseGame),
    SeedEntry("Globber", Tag.BaseGame),
    SeedEntry("Smasher", Tag.BaseGame),
    SeedEntry("Cyber Eagle", Tag.BaseGame),
    SeedEntry("Probe", Tag.BaseGame),
    SeedEntry("Sledge's Shotty", Tag.BaseGame),
    SeedEntry("Viral Marketer", Tag.BaseGame),
    SeedEntry("Striker", Tag.BaseGame),
    SeedEntry("Flakker", Tag.BaseGame),
    SeedEntry("Boganella", Tag.BaseGame),
    SeedEntry("Moonface", Tag.BaseGame),
    SeedEntry("Boomacorn", Tag.BaseGame),
    SeedEntry("Too Scoops", Tag.BaseGame),
    SeedEntry("Bullpup", Tag.BaseGame),
    SeedEntry("Octo", Tag.BaseGame),
    SeedEntry("Jack-o'-Cannon", Tag.BaseGame),
    SeedEntry("Torguemada", Tag.BaseGame),
    SeedEntry("Wombat", Tag.BaseGame),
    SeedEntry("Torrent", Tag.BaseGame),
    SeedEntry("Fatale", Tag.BaseGame),
    SeedEntry("HellFire", Tag.BaseGame),
    SeedEntry("IVF", Tag.BaseGame),
    SeedEntry("Marek's Mouth", Tag.BaseGame),
    SeedEntry("Meat Grinder", Tag.BaseGame),
    SeedEntry("Black Snake", Tag.BaseGame),
    SeedEntry("Fridgia", Tag.BaseGame),
    SeedEntry("Frostfire", Tag.BaseGame),
    SeedEntry("Pitchfork", Tag.BaseGame),
    SeedEntry("Invader", Tag.BaseGame),
    SeedEntry("Skullmasher", Tag.BaseGame),
    SeedEntry("Magma", Tag.BaseGame),
    SeedEntry("Longnail", Tag.BaseGame),
    SeedEntry("Wet Week", Tag.BaseGame),
    SeedEntry("Razorback", Tag.BaseGame),
    SeedEntry("The Machine", Tag.BaseGame),
    SeedEntry("Fremington's Edge", Tag.BaseGame),
    SeedEntry("Boss Nova", Tag.BaseGame),
    SeedEntry("Company Man", Tag.BaseGame),
    SeedEntry("Moonscaper", Tag.BaseGame),
    SeedEntry("Fast Talker", Tag.BaseGame),
    SeedEntry("Naught", Tag.BaseGame),
    SeedEntry("Bandit Assault Rifle", Tag.BaseGame|Tag.ClaptasticVoyage),
    SeedEntry("Dahl Assault Rifle", Tag.BaseGame|Tag.ClaptasticVoyage),
    SeedEntry("Jakobs Assault Rifle", Tag.BaseGame|Tag.ClaptasticVoyage),
    SeedEntry("Torgue Assault Rifle", Tag.BaseGame|Tag.ClaptasticVoyage),
    SeedEntry("Vladof Assault Rifle", Tag.BaseGame|Tag.ClaptasticVoyage),
    SeedEntry("Dahl Laser", Tag.BaseGame|Tag.ClaptasticVoyage),
    SeedEntry("Hyperion Laser", Tag.BaseGame|Tag.ClaptasticVoyage),
    SeedEntry("Old Hyperion Laser", Tag.BaseGame),
    SeedEntry("Maliwan Laser", Tag.BaseGame|Tag.ClaptasticVoyage),
    SeedEntry("Tediore Laser", Tag.BaseGame|Tag.ClaptasticVoyage),
    SeedEntry("Bandit Pistol", Tag.BaseGame|Tag.ClaptasticVoyage),
    SeedEntry("Dahl Pistol", Tag.BaseGame|Tag.ClaptasticVoyage),
    SeedEntry("Hyperion Pistol", Tag.BaseGame|Tag.ClaptasticVoyage),
    SeedEntry("Jakobs Pistol", Tag.BaseGame|Tag.ClaptasticVoyage),
    SeedEntry("Maliwan Pistol", Tag.BaseGame|Tag.ClaptasticVoyage),
    SeedEntry("Old Hyperion Pistol", Tag.BaseGame|Tag.ClaptasticVoyage),
    SeedEntry("Tediore Pistol", Tag.BaseGame|Tag.ClaptasticVoyage),
    SeedEntry("Torgue Pistol", Tag.BaseGame|Tag.ClaptasticVoyage),
    SeedEntry("Vladof Pistol", Tag.BaseGame|Tag.ClaptasticVoyage),
    SeedEntry("Bandit Rocket Launcher", Tag.BaseGame|Tag.ClaptasticVoyage),
    SeedEntry("Maliwan Rocket Launcher", Tag.BaseGame|Tag.ClaptasticVoyage),
    SeedEntry("Tediore Rocket Launcher", Tag.BaseGame|Tag.ClaptasticVoyage),
    SeedEntry("Torgue Rocket Launcher", Tag.BaseGame|Tag.ClaptasticVoyage),
    SeedEntry("Vladof Rocket Launcher", Tag.BaseGame|Tag.ClaptasticVoyage),
    SeedEntry("Bandit Shotgun", Tag.BaseGame|Tag.ClaptasticVoyage),
    SeedEntry("Hyperion Shotgun", Tag.BaseGame|Tag.ClaptasticVoyage),
    SeedEntry("Jakobs Shotgun", Tag.BaseGame|Tag.ClaptasticVoyage),
    SeedEntry("Old Hyperion Shotgun", Tag.BaseGame|Tag.ClaptasticVoyage),
    SeedEntry("Tediore Shotgun", Tag.BaseGame|Tag.ClaptasticVoyage),
    SeedEntry("Torgue Shotgun", Tag.BaseGame|Tag.ClaptasticVoyage),
    SeedEntry("Bandit SMG", Tag.BaseGame|Tag.ClaptasticVoyage),
    SeedEntry("Dahl SMG", Tag.BaseGame|Tag.ClaptasticVoyage),
    SeedEntry("Hyperion SMG", Tag.BaseGame|Tag.ClaptasticVoyage),
    SeedEntry("Old Hyperion SMG", Tag.BaseGame|Tag.ClaptasticVoyage),
    SeedEntry("Maliwan SMG", Tag.BaseGame|Tag.ClaptasticVoyage),
    SeedEntry("Tediore SMG", Tag.BaseGame|Tag.ClaptasticVoyage),
    SeedEntry("Dahl Sniper", Tag.BaseGame|Tag.ClaptasticVoyage),
    SeedEntry("Hyperion Sniper", Tag.BaseGame|Tag.ClaptasticVoyage),
    SeedEntry("Old Hyperion Sniper", Tag.BaseGame),
    SeedEntry("Jakobs Sniper", Tag.BaseGame|Tag.ClaptasticVoyage),
    SeedEntry("Maliwan Sniper", Tag.BaseGame|Tag.ClaptasticVoyage),
    SeedEntry("Vladof Sniper", Tag.BaseGame|Tag.ClaptasticVoyage),
    SeedEntry("Fire Burst / Tesla / Corrosive Cloud / Cryo", Tag.BaseGame),
    SeedEntry("Bouncing Betty", Tag.BaseGame),
    SeedEntry("Sheila", Tag.BaseGame),
    SeedEntry("MIRV", Tag.BaseGame),
    SeedEntry("Merv", Tag.BaseGame),
    SeedEntry("Grenade", Tag.BaseGame),
    SeedEntry("Gr'nade", Tag.BaseGame),
    SeedEntry("Singularity", Tag.BaseGame),
    SeedEntry("Transfusion", Tag.BaseGame),
    SeedEntry("Kiss of Death", Tag.BaseGame),
    SeedEntry("Baby Boomer", Tag.BaseGame),
    SeedEntry("Contraband Sky Rocket", Tag.BaseGame),
    SeedEntry("Snowball", Tag.BaseGame),
    SeedEntry("Bonus Package", Tag.BaseGame),
    SeedEntry("Bouncing Bazza", Tag.BaseGame),
    SeedEntry("Fire Bee", Tag.BaseGame),
    SeedEntry("Four Seasons", Tag.BaseGame),
    SeedEntry("Leech", Tag.BaseGame),
    SeedEntry("Nasty Surprise", Tag.BaseGame),
    SeedEntry("Pandemic", Tag.BaseGame),
    SeedEntry("Quasar", Tag.BaseGame),
    SeedEntry("Rolling Thunder", Tag.BaseGame),
    SeedEntry("Storm Front", Tag.BaseGame),
    SeedEntry("Shield", Tag.BaseGame),
    SeedEntry("Absorb Shield", Tag.BaseGame),
    SeedEntry("Adaptive Shield", Tag.BaseGame),
    SeedEntry("Amplify Shield", Tag.BaseGame),
    SeedEntry("Booster Shield", Tag.BaseGame),
    SeedEntry("Maylay Shield", Tag.BaseGame),
    SeedEntry("Nova Shield", Tag.BaseGame),
    SeedEntry("Spike Shield", Tag.BaseGame),
    SeedEntry("Turtle Shield", Tag.BaseGame),
    SeedEntry("Avalanche", Tag.BaseGame),
    SeedEntry("Bigg Thumppr", Tag.BaseGame),
    SeedEntry("Black Hole", Tag.BaseGame),
    SeedEntry("Fabled Tortoise", Tag.BaseGame),
    SeedEntry("Kala", Tag.BaseGame),
    SeedEntry("Prismatic Bulwark", Tag.BaseGame),
    SeedEntry("Reogenator", Tag.BaseGame),
    SeedEntry("The Cradle", Tag.BaseGame),
    SeedEntry("The Sham", Tag.BaseGame),
    SeedEntry("The Shooting Star", Tag.BaseGame),
    SeedEntry("Whisky Tango Foxtrot", Tag.BaseGame),
    SeedEntry("Asteroid Belt", Tag.BaseGame),
    SeedEntry("Deadly Bloom", Tag.BaseGame),
    SeedEntry("Haymaker", Tag.BaseGame),
    SeedEntry("Miss Moxxi's Slammer", Tag.BaseGame),
    SeedEntry("Rapid Release", Tag.BaseGame),
    SeedEntry("Sunshine", Tag.BaseGame),
    SeedEntry("Supernova", Tag.BaseGame),
    SeedEntry("Acrobat Oz Kit", Tag.BaseGame),
    SeedEntry("Clear Skies Oz Kit", Tag.BaseGame),
    SeedEntry("Bomber Oz Kit", Tag.BaseGame),
    SeedEntry("Hyperventilator Oz Kit", Tag.BaseGame),
    SeedEntry("Juggernaut Oz Kit", Tag.BaseGame),
    SeedEntry("Precision Strike Oz Kit", Tag.BaseGame),
    SeedEntry("Strafing Run Oz Kit", Tag.BaseGame),
    SeedEntry("Tranquility Oz Kit", Tag.BaseGame),
    SeedEntry("Shotgun Duality Oz Kit", Tag.BaseGame),
    SeedEntry("Sniper Duality Oz Kit", Tag.BaseGame),
    SeedEntry("Laser Duality Oz Kit", Tag.BaseGame),
    SeedEntry("Assault Rifle Duality Oz Kit", Tag.BaseGame),
    SeedEntry("Pistol Duality Oz Kit", Tag.BaseGame),
    SeedEntry("SMG Duality Oz Kit", Tag.BaseGame),
    SeedEntry("Launcher Duality Oz Kit", Tag.BaseGame),
    SeedEntry("Elemental Duality Oz Kit", Tag.BaseGame),
    SeedEntry("Melee Duality Oz Kit", Tag.BaseGame),
    SeedEntry("3DD1.E", Tag.BaseGame),
    SeedEntry("Ack Ack", Tag.BaseGame),
    SeedEntry("Moonlight Saga", Tag.BaseGame),
    SeedEntry("Oxidizer", Tag.BaseGame),
    SeedEntry("Support Relay", Tag.BaseGame),
    SeedEntry("Cathartic Oz Kit", Tag.BaseGame),
    SeedEntry("Freedom Oz Kit", Tag.BaseGame),
    SeedEntry("Invigoration Oz Kit", Tag.BaseGame),
    SeedEntry("Perdy Lights", Tag.BaseGame),
    SeedEntry("Springs' Oz Kit", Tag.BaseGame),
    SeedEntry("Systems Purge", Tag.BaseGame),
    SeedEntry("Fusillade", Tag.ClaptasticVoyage),
    SeedEntry("Luck Cannon", Tag.ClaptasticVoyage),
    SeedEntry("Proletarian Revolution", Tag.ClaptasticVoyage),
    SeedEntry("Longest Yard", Tag.ClaptasticVoyage),
    SeedEntry("Absolute Zero", Tag.ClaptasticVoyage),
    SeedEntry("Thunderfire", Tag.ClaptasticVoyage),
    SeedEntry("Laser Disker", Tag.ClaptasticVoyage),
    SeedEntry("Tannis' Laser of Enlightenment", Tag.ClaptasticVoyage),
    SeedEntry("MINAC's Atonement", Tag.ClaptasticVoyage),
    SeedEntry("Kaneda's Laser", Tag.ClaptasticVoyage),
    SeedEntry("Flayer", Tag.ClaptasticVoyage),
    SeedEntry("Cheat Code", Tag.ClaptasticVoyage),
    SeedEntry("Omni-Cannon", Tag.ClaptasticVoyage),
    SeedEntry("/He4rtf;ull Spl0Dge..r", Tag.ClaptasticVoyage),
    SeedEntry("Party Popper", Tag.ClaptasticVoyage),
    SeedEntry("Hard Reboot", Tag.ClaptasticVoyage),
    SeedEntry("%Cu+ie^_^ki||er", Tag.ClaptasticVoyage),
    SeedEntry("Meganade", Tag.ClaptasticVoyage),
    SeedEntry("Data Scrubber", Tag.ClaptasticVoyage),
    SeedEntry("M0RQ", Tag.ClaptasticVoyage),
    SeedEntry("Rerouter", Tag.ClaptasticVoyage),
    SeedEntry("Shield of Ages", Tag.ClaptasticVoyage),
    SeedEntry("Cry Baby", Tag.Holodome),
    SeedEntry("Wiggly Cry Baby", Tag.Holodome),
    SeedEntry("Berrigan", Tag.Holodome),
    SeedEntry("T4s-R", Tag.Holodome),
    SeedEntry("Party Line", Tag.Holodome),
    SeedEntry("Boxxy Gunn", Tag.Holodome),
    SeedEntry("Plunkett", Tag.Holodome),
)


Locations = (
    SeedEntry("Other: World Uniques", Tag.BaseGame|Tag.Miscellaneous|Tag.Excluded),
    SeedEntry("Enemy: Flame Knuckle", Tag.BaseGame|Tag.UniqueEnemy|Tag.Excluded),
    SeedEntry("Mission: Tales from Elpis", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Enemy: Son of Flamey", Tag.BaseGame|Tag.UniqueEnemy),
    SeedEntry("Enemy: Grandson of Flamey", Tag.BaseGame|Tag.UniqueEnemy),
    SeedEntry("Enemy: Badass Kraggon", Tag.BaseGame|Tag.VeryRareEnemy),
    SeedEntry("Enemy: Phonic Kraggon", Tag.BaseGame|Tag.RareEnemy),
    SeedEntry("Mission: Land Among the Stars", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Mission: Follow Your Heart", Tag.BaseGame|Tag.LongMission),
    SeedEntry("Enemy: Deadlift", Tag.BaseGame|Tag.SlowEnemy),
    SeedEntry("Mission: Last Requests", Tag.BaseGame|Tag.LongMission),
    SeedEntry("Enemy: Tom Thorson", Tag.BaseGame|Tag.LongMission|Tag.MissionEnemy),
    SeedEntry("Enemy: Squat", Tag.BaseGame|Tag.LongMission|Tag.MissionEnemy),
    SeedEntry("Enemy: Nel (Called a Dick)", Tag.BaseGame|Tag.LongMission|Tag.MissionEnemy),
    SeedEntry("Enemy: Nel", Tag.BaseGame|Tag.SlowEnemy),
    SeedEntry("Mission: Nova? No Problem!", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Other: Janey's Chest", Tag.BaseGame|Tag.ShortMission|Tag.Miscellaneous),
    SeedEntry("Mission: Torgue-o! Torgue-o! (Turn in Janey)", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Mission: Torgue-o! Torgue-o! (Turn in Lava)", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Enemy: Antagonized Kraggon", Tag.BaseGame|Tag.ShortMission|Tag.MissionEnemy),
    SeedEntry("Mission: Wherefore Art Thou?", Tag.BaseGame|Tag.LongMission|Tag.VehicleMission),
    SeedEntry("Enemy: Maureen", Tag.BaseGame|Tag.LongMission|Tag.VehicleMission|Tag.MissionEnemy),
    SeedEntry("Mission: All the Little Creatures", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Enemy: Even-More-Disgusting Tork", Tag.BaseGame|Tag.UniqueEnemy),
    SeedEntry("Other: Sword in the Stone", Tag.BaseGame|Tag.Miscellaneous),
    SeedEntry("Enemy: Swagman", Tag.BaseGame|Tag.UniqueEnemy),
    SeedEntry("Mission: Recruitment Drive", Tag.BaseGame|Tag.VehicleMission),
    SeedEntry("Enemy: Magma Rivers", Tag.BaseGame|Tag.UniqueEnemy),
    SeedEntry("Enemy: Wally Wrong", Tag.BaseGame|Tag.UniqueEnemy),
    SeedEntry("Enemy: Fair Dinkum", Tag.BaseGame|Tag.UniqueEnemy),
    SeedEntry("Mission: The Empty Billabong", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Enemy: Jolly Swagman", Tag.BaseGame|Tag.ShortMission|Tag.MissionEnemy),
    SeedEntry("Enemy: Red", Tag.BaseGame|Tag.UniqueEnemy),
    SeedEntry("Enemy: Belly", Tag.BaseGame|Tag.UniqueEnemy),
    SeedEntry("Mission: Grinders", Tag.BaseGame|Tag.VeryLongMission),
    SeedEntry("Enemy: Rooster Booster", Tag.BaseGame|Tag.UniqueEnemy),
    SeedEntry("Mission: To Arms!", Tag.BaseGame|Tag.VeryLongMission),
    SeedEntry("Enemy: PLA Member Tim Pot", Tag.BaseGame|Tag.VeryLongMission|Tag.MissionEnemy),
    SeedEntry("Enemy: PLA Member Tom Pot", Tag.BaseGame|Tag.VeryLongMission|Tag.MissionEnemy),
    SeedEntry("Enemy: PLA Member Tum Pot", Tag.BaseGame|Tag.VeryLongMission|Tag.MissionEnemy),
    SeedEntry("Mission: Bunch of Ice Holes (Turn in Nurse Nina)", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Mission: Bunch of Ice Holes (Turn in B4R-BOT)", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Enemy: Giant Shuggurath of Ice", Tag.BaseGame|Tag.UniqueEnemy),
    SeedEntry("Mission: Pop Racing", Tag.BaseGame|Tag.VehicleMission),
    SeedEntry("Enemy: Lunestalker Snr", Tag.BaseGame|Tag.UniqueEnemy),
    SeedEntry("Mission: Zapped 1.0", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Mission: Zapped 2.0", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Mission: Zapped 3.0", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Mission: Boomshakalaka", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Enemy: Dunks Watson", Tag.BaseGame|Tag.ShortMission|Tag.MissionEnemy),
    SeedEntry("Mission: Space Slam", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Enemy: Tork Dredger", Tag.BaseGame|Tag.RareEnemy),
    SeedEntry("Mission: Boarding Party", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Mission: Cleanliness Uprising", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Mission: The Bestest Story Ever Told", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Mission: An Urgent Message", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Mission: Don't Shoot the Messenger", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Mission: Guardian Hunter", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Mission: Sterwin Forever", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Mission: Home Delivery", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Mission: Hot Head", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Mission: Kill Meg", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Mission: Paint Job", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Mission: Handsome AI", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Mission: Return of Captain Chef", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Mission: Rough Love", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Mission: The Secret Chamber", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Mission: To the Moon", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Mission: Things That Go Boom", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Mission: Fresh Air", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Mission: Lab 19", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Mission: Lock and Load", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Mission: Infinite Loop", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Mission: Picking Up the Pieces", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Mission: Red, Then Dead", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Mission: It Ain't Rocket Surgery", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Mission: The Don", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Mission: These are the Bots", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Mission: Z8N-TP", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Mission: Sub-Level 13", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Mission: Sub-Level 13: Part 2", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Mission: Treasures of ECHO Madre", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Mission: Voice Over", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Mission: The Voyage of Captain Chef", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Mission: Wiping the Slate", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Mission: Nothing is Never an Option", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Mission: Another Pickle", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Mission: Quarantine: Back On Schedule", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Mission: Don't Get Cocky", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Mission: Eradicate!", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Mission: In Perfect Hibernation", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Mission: Quarantine: Infestation", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Mission: No Such Thing as a Free Launch", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Mission: Trouble with Space Hurps", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Mission: l33t h4X0rz", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Mission: A Deadlier Game", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Mission: Byte Club", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Mission: Chip's Data Mining Adventure", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Mission: 3G0-TP", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Mission: 1D-TP", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Mission: Rose Tinting", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Mission: Corrosion of Dignity", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Mission: Spyware Who Came in from the Cold", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Mission: You Can Stop the Music", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Mission: The Sum of Some Fears", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Mission: 5UP4-3G0-TP", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Mission: The Temple of Boom", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Mission: h4X0rz", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Mission: Digistructed Madness: Round 1", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Mission: Digistructed Madness: Round 2", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Mission: Digistructed Madness: Round 3", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Mission: Digistructed Madness: Round 4", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Mission: Digistructed Madness: Round 5", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Mission: Digistructed Madness: The Badass Round", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Mission: DAHL Combat Training: Round 1", Tag.ShockDrop|Tag.LongMission|Tag.Slaughter),
    SeedEntry("Mission: DAHL Combat Training: Round 2", Tag.ShockDrop|Tag.LongMission|Tag.Slaughter),
    SeedEntry("Mission: DAHL Combat Training: Round 3", Tag.ShockDrop|Tag.LongMission|Tag.Slaughter),
    SeedEntry("Mission: DAHL Combat Training: Round 4", Tag.ShockDrop|Tag.LongMission|Tag.Slaughter),
    SeedEntry("Mission: DAHL Combat Training: Round 5", Tag.ShockDrop|Tag.LongMission|Tag.Slaughter),
)
