from . import Tag
from ..seed import SeedEntry

Tags = (
    Tag.BaseGame
    | Tag.PiratesBooty
    | Tag.CampaignOfCarnage
    | Tag.HammerlocksHunt
    | Tag.DragonKeep
    | Tag.FightForSanctuary
    | Tag.BloodyHarvest
    | Tag.WattleGobbler
    | Tag.MercenaryDay
    | Tag.WeddingDayMassacre
    | Tag.SonOfCrawmerax
    | Tag.UVHMPack
    | Tag.DigistructPeak
    | Tag.ShortMission
    | Tag.LongMission
    | Tag.VeryLongMission
    | Tag.Slaughter
    | Tag.UniqueEnemy
    | Tag.SlowEnemy
    | Tag.RareEnemy
    | Tag.VeryRareEnemy
    | Tag.MobFarm
    | Tag.Raid
    | Tag.MissionLocation
    | Tag.EvolvedEnemy
    | Tag.DigistructEnemy
    | Tag.Vendor
    | Tag.Miscellaneous
    | Tag.DuplicateItems
    | Tag.EnableHints
    | Tag.VehicleMission
    | Tag.Freebie
)

# fmt: off

Items = (
    SeedEntry("Blue Infiltrator / Beast / Banshee / Engineer / Slab / Roboteer", Tag.BaseGame),
    SeedEntry("Blue Killer / Berserker / Binder / Grenadier / Meat / Zapper", Tag.BaseGame),
    SeedEntry("Blue Ninja / War Dog / Cat / Gunner / Crunch / Jill of All Trades", Tag.BaseGame),
    SeedEntry("Blue Professional / Devastator / Fox / Pointman / Toast / Punk", Tag.BaseGame),
    SeedEntry("Blue Shot / Raider / Matriarch / Rifleman / Torch / Anarchist", Tag.BaseGame),
    SeedEntry("Blue Sniper / Renegade / Nurse / Shock Trooper / Sickle / Technophile", Tag.BaseGame),
    SeedEntry("Blue Spy / Tank / Trickster / Specialist / Wound / Prodigy", Tag.BaseGame),
    SeedEntry("Blue Stalker / Titan / Warder / Tactician / Blister / Catalyst", Tag.BaseGame),
    SeedEntry("Blue Survivor / Hoarder / Witch / Veteran / Reaper / Sweetheart", Tag.BaseGame),
    SeedEntry("Purple Infiltrator / Beast / Banshee / Engineer / Slab / Roboteer", Tag.BaseGame),
    SeedEntry("Purple Killer / Berserker / Binder / Grenadier / Meat / Zapper", Tag.BaseGame),
    SeedEntry("Purple Ninja / War Dog / Cat / Gunner / Crunch / Jill of All Trades", Tag.BaseGame),
    SeedEntry("Purple Professional / Devastator / Fox / Pointman / Toast / Punk", Tag.BaseGame),
    SeedEntry("Purple Shot / Raider / Matriarch / Rifleman / Torch / Anarchist", Tag.BaseGame),
    SeedEntry("Purple Sniper / Renegade / Nurse / Shock Trooper / Sickle / Technophile", Tag.BaseGame),
    SeedEntry("Purple Spy / Tank / Trickster / Specialist / Wound / Prodigy", Tag.BaseGame),
    SeedEntry("Purple Stalker / Titan / Warder / Tactician / Blister / Catalyst", Tag.BaseGame),
    SeedEntry("Purple Survivor / Hoarder / Witch / Veteran / Reaper / Sweetheart", Tag.BaseGame),
    SeedEntry("Blue Rogue / Monk / Cleric / Ranger / Barbarian / Necromancer", Tag.DragonKeep),
    SeedEntry("Purple Rogue / Monk / Cleric / Ranger / Barbarian / Necromancer", Tag.DragonKeep),
    SeedEntry("Legendary Hunter / Berserker / Siren / Soldier / Psycho / Mechromancer", Tag.BaseGame),
    SeedEntry("Slayer Of Terramorphous", Tag.BaseGame),
    SeedEntry("Legendary Killer / Gunzerker / Binder / Engineer / Sickle / Anarchist", Tag.DigistructPeak),
    SeedEntry("Legendary Ninja / Hoarder / Cat / Pointman / Torch / Catalyst", Tag.DigistructPeak),
    SeedEntry("Legendary Sniper / Titan / Nurse / Ranger / Reaper / Roboteer", Tag.DigistructPeak),
    SeedEntry("Aggression Relic", Tag.BaseGame),
    SeedEntry("Elemental Relic", Tag.BaseGame),
    SeedEntry("Proficiency Relic", Tag.BaseGame),
    SeedEntry("Protection Relic", Tag.BaseGame),
    SeedEntry("Resistance Relic", Tag.BaseGame),
    SeedEntry("Stockpile Relic", Tag.BaseGame),
    SeedEntry("Strength Relic", Tag.BaseGame),
    SeedEntry("Tenacity Relic", Tag.BaseGame),
    SeedEntry("Vitality Relic", Tag.BaseGame),
    SeedEntry("Bandit Allegiance Relic", Tag.BaseGame),
    SeedEntry("Dahl Allegiance Relic", Tag.BaseGame),
    SeedEntry("Hyperion Allegiance Relic", Tag.BaseGame),
    SeedEntry("Jakobs Allegiance Relic", Tag.BaseGame),
    SeedEntry("Maliwan Allegiance Relic", Tag.BaseGame),
    SeedEntry("Tediore Allegiance Relic", Tag.BaseGame),
    SeedEntry("Torgue Allegiance Relic", Tag.BaseGame),
    SeedEntry("Vladof Allegiance Relic", Tag.BaseGame),
    SeedEntry("The Afterburner", Tag.BaseGame),
    SeedEntry("Deputy's Badge", Tag.BaseGame),
    SeedEntry("Moxxi's Endowment", Tag.BaseGame),
    SeedEntry("Lucrative Opportunity", Tag.BaseGame),
    SeedEntry("Sheriff's Badge", Tag.BaseGame),
    SeedEntry("Blood of Terramorphous", Tag.BaseGame),
    SeedEntry("Vault Hunter's Relic", Tag.BaseGame),
    SeedEntry("Fire Burst / Tesla / Corrosive Cloud", Tag.BaseGame),
    SeedEntry("Bouncing Betty", Tag.BaseGame),
    SeedEntry("Jumpin Biddy", Tag.BaseGame),
    SeedEntry("MIRV", Tag.BaseGame),
    SeedEntry("Mruv / Mrvur / Murrv / Muvr / Muvv", Tag.BaseGame),
    SeedEntry("Singularity", Tag.BaseGame),
    SeedEntry("Grenade", Tag.BaseGame),
    SeedEntry("gurnade", Tag.BaseGame),
    SeedEntry("Transfusion", Tag.BaseGame),
    SeedEntry("Fuster Cluck", Tag.BaseGame),
    SeedEntry("Kiss of Death", Tag.BaseGame),
    SeedEntry("Sky Rocket", Tag.BaseGame),
    SeedEntry("Breath of Terramorphous", Tag.BaseGame),
    SeedEntry("Bonus Package", Tag.BaseGame),
    SeedEntry("Bouncing Bonny", Tag.BaseGame),
    SeedEntry("Fastball", Tag.BaseGame),
    SeedEntry("Fire Bee", Tag.BaseGame),
    SeedEntry("Leech", Tag.BaseGame),
    SeedEntry("Nasty Surprise", Tag.BaseGame),
    SeedEntry("Pandemic", Tag.BaseGame),
    SeedEntry("Quasar", Tag.BaseGame),
    SeedEntry("Rolling Thunder", Tag.BaseGame),
    SeedEntry("Storm Front", Tag.BaseGame),
    SeedEntry("Shield", Tag.BaseGame),
    SeedEntry("Absorb Shield", Tag.BaseGame),
    SeedEntry("Adaptive Shield", Tag.BaseGame),
    SeedEntry("Amplify Shield", Tag.BaseGame),
    SeedEntry("Booster Shield", Tag.BaseGame),
    SeedEntry("Maylay Shield", Tag.BaseGame),
    SeedEntry("Nova Shield", Tag.BaseGame),
    SeedEntry("Spike Shield", Tag.BaseGame),
    SeedEntry("Turtle Shield", Tag.BaseGame),
    SeedEntry("1340 Shield", Tag.BaseGame),
    SeedEntry("Aequitas", Tag.BaseGame),
    SeedEntry("Pot O' Gold", Tag.BaseGame),
    SeedEntry("Deadly Bloom", Tag.BaseGame),
    SeedEntry("Order", Tag.BaseGame),
    SeedEntry("Cracked Sash", Tag.BaseGame),
    SeedEntry("Love Thumper", Tag.BaseGame),
    SeedEntry("The Sham", Tag.BaseGame),
    SeedEntry("The Transformer", Tag.BaseGame),
    SeedEntry("Whisky Tango Foxtrot", Tag.BaseGame),
    SeedEntry("Neogenator", Tag.BaseGame),
    SeedEntry("The Bee", Tag.BaseGame),
    SeedEntry("Fabled Tortoise", Tag.BaseGame),
    SeedEntry("Flame of the Firehawk", Tag.BaseGame),
    SeedEntry("Black Hole", Tag.BaseGame),
    SeedEntry("Hide of Terramorphous", Tag.BaseGame),
    SeedEntry("Impaler", Tag.BaseGame),
    SeedEntry("The Cradle", Tag.BaseGame),
    SeedEntry("Bandit Assault Rifle", Tag.BaseGame|Tag.DragonKeep),
    SeedEntry("Dahl Assault Rifle", Tag.BaseGame|Tag.DragonKeep),
    SeedEntry("Jakobs Assault Rifle", Tag.BaseGame|Tag.DragonKeep),
    SeedEntry("Torgue Assault Rifle", Tag.BaseGame|Tag.DragonKeep),
    SeedEntry("Vladof Assault Rifle", Tag.BaseGame|Tag.DragonKeep),
    SeedEntry("E-tech Assault Rifle", Tag.BaseGame),
    SeedEntry("Bandit Rocket Launcher", Tag.BaseGame),
    SeedEntry("Tediore Rocket Launcher", Tag.BaseGame),
    SeedEntry("Vladof Rocket Launcher", Tag.BaseGame),
    SeedEntry("Maliwan Rocket Launcher", Tag.BaseGame),
    SeedEntry("Torgue Rocket Launcher", Tag.BaseGame),
    SeedEntry("E-tech Rocket Launcher", Tag.BaseGame),
    SeedEntry("Bandit Pistol", Tag.BaseGame|Tag.DragonKeep),
    SeedEntry("Tediore Pistol", Tag.BaseGame|Tag.DragonKeep),
    SeedEntry("Dahl Pistol", Tag.BaseGame|Tag.DragonKeep),
    SeedEntry("Vladof Pistol", Tag.BaseGame|Tag.DragonKeep),
    SeedEntry("Torgue Pistol", Tag.BaseGame|Tag.DragonKeep),
    SeedEntry("Maliwan Pistol", Tag.BaseGame|Tag.DragonKeep),
    SeedEntry("Jakobs Pistol", Tag.BaseGame|Tag.DragonKeep),
    SeedEntry("Hyperion Pistol", Tag.BaseGame|Tag.DragonKeep),
    SeedEntry("E-tech Pistol", Tag.BaseGame),
    SeedEntry("Bandit Shotgun", Tag.BaseGame|Tag.DragonKeep),
    SeedEntry("Tediore Shotgun", Tag.BaseGame|Tag.DragonKeep),
    SeedEntry("Torgue Shotgun", Tag.BaseGame|Tag.DragonKeep),
    SeedEntry("Jakobs Shotgun", Tag.BaseGame|Tag.DragonKeep),
    SeedEntry("Hyperion Shotgun", Tag.BaseGame|Tag.DragonKeep),
    SeedEntry("E-tech Shotgun", Tag.BaseGame),
    SeedEntry("Bandit SMG", Tag.BaseGame|Tag.DragonKeep),
    SeedEntry("Tediore SMG", Tag.BaseGame|Tag.DragonKeep),
    SeedEntry("Dahl SMG", Tag.BaseGame|Tag.DragonKeep),
    SeedEntry("Maliwan SMG", Tag.BaseGame|Tag.DragonKeep),
    SeedEntry("Hyperion SMG", Tag.BaseGame|Tag.DragonKeep),
    SeedEntry("E-tech SMG", Tag.BaseGame),
    SeedEntry("Dahl Sniper Rifle", Tag.BaseGame|Tag.DragonKeep),
    SeedEntry("Vladof Sniper Rifle", Tag.BaseGame|Tag.DragonKeep),
    SeedEntry("Maliwan Sniper Rifle", Tag.BaseGame|Tag.DragonKeep),
    SeedEntry("Jakobs Sniper Rifle", Tag.BaseGame|Tag.DragonKeep),
    SeedEntry("Hyperion Sniper Rifle", Tag.BaseGame|Tag.DragonKeep),
    SeedEntry("E-tech Sniper Rifle", Tag.BaseGame),
    SeedEntry("Gearbox SMG", Tag.BaseGame),
    SeedEntry("Lascaux", Tag.BaseGame),
    SeedEntry("Bad Touch", Tag.BaseGame),
    SeedEntry("Good Touch", Tag.BaseGame),
    SeedEntry("Commerce", Tag.BaseGame),
    SeedEntry("Bone Shredder", Tag.BaseGame),
    SeedEntry("Chulainn", Tag.BaseGame),
    SeedEntry("Bane", Tag.BaseGame),
    SeedEntry("Gwen's Head", Tag.BaseGame),
    SeedEntry("Judge", Tag.BaseGame),
    SeedEntry("Tinderbox", Tag.BaseGame),
    SeedEntry("Law", Tag.BaseGame),
    SeedEntry("Teapot", Tag.BaseGame),
    SeedEntry("Shotgun Fibber", Tag.BaseGame),
    SeedEntry("Ricochet Fibber", Tag.BaseGame),
    SeedEntry("Crit Fibber", Tag.BaseGame),
    SeedEntry("Rubi", Tag.BaseGame),
    SeedEntry("Veritas", Tag.BaseGame),
    SeedEntry("Dahlminator", Tag.BaseGame),
    SeedEntry("Lady Fist", Tag.BaseGame),
    SeedEntry("Gearbox Sniper Rifle", Tag.BaseGame),
    SeedEntry("Fremington's Edge", Tag.BaseGame),
    SeedEntry("Buffalo", Tag.BaseGame),
    SeedEntry("Trespasser", Tag.BaseGame),
    SeedEntry("Sloth", Tag.BaseGame),
    SeedEntry("Morningstar", Tag.BaseGame),
    SeedEntry("Chère-amie", Tag.BaseGame),
    SeedEntry("Dog", Tag.BaseGame),
    SeedEntry("Teeth of Terramorphous", Tag.BaseGame),
    SeedEntry("Blockhead", Tag.BaseGame),
    SeedEntry("Landscaper", Tag.BaseGame),
    SeedEntry("Triquetra", Tag.BaseGame),
    SeedEntry("Heart Breaker", Tag.BaseGame),
    SeedEntry("Octo", Tag.BaseGame),
    SeedEntry("RokSalt", Tag.BaseGame),
    SeedEntry("Shotgun 1340", Tag.BaseGame),
    SeedEntry("Tidal Wave", Tag.BaseGame),
    SeedEntry("Hive", Tag.BaseGame),
    SeedEntry("Creamer", Tag.BaseGame),
    SeedEntry("Roaster", Tag.BaseGame),
    SeedEntry("Gearbox Assault Rifle", Tag.BaseGame),
    SeedEntry("Hail", Tag.BaseGame),
    SeedEntry("Scorpio", Tag.BaseGame),
    SeedEntry("Evil Smasher", Tag.BaseGame),
    SeedEntry("Stomper", Tag.BaseGame),
    SeedEntry("Sledge's Shotgun", Tag.BaseGame),
    SeedEntry("Striker", Tag.BaseGame),
    SeedEntry("Deliverance", Tag.BaseGame),
    SeedEntry("Flakker", Tag.BaseGame),
    SeedEntry("Conference Call", Tag.BaseGame),
    SeedEntry("Nukem", Tag.BaseGame),
    SeedEntry("Pyrophobia", Tag.BaseGame),
    SeedEntry("Bunny", Tag.BaseGame),
    SeedEntry("Badaboom", Tag.BaseGame),
    SeedEntry("Mongol", Tag.BaseGame),
    SeedEntry("Norfleet", Tag.BaseGame),
    SeedEntry("Bitch", Tag.BaseGame),
    SeedEntry("Emperor", Tag.BaseGame),
    SeedEntry("Baby Maker", Tag.BaseGame),
    SeedEntry("Hellfire", Tag.BaseGame),
    SeedEntry("Slagga", Tag.BaseGame),
    SeedEntry("Thunderball Fists", Tag.BaseGame),
    SeedEntry("Hornet", Tag.BaseGame),
    SeedEntry("Gub", Tag.BaseGame),
    SeedEntry("Maggie", Tag.BaseGame),
    SeedEntry("Infinity", Tag.BaseGame),
    SeedEntry("Gunerang", Tag.BaseGame),
    SeedEntry("Unkempt Harold", Tag.BaseGame),
    SeedEntry("Logan's Gun", Tag.BaseGame),
    SeedEntry("Lyudmila", Tag.BaseGame),
    SeedEntry("Skullmasher", Tag.BaseGame),
    SeedEntry("Invader", Tag.BaseGame),
    SeedEntry("Pitchfork", Tag.BaseGame),
    SeedEntry("Volcano", Tag.BaseGame),
    SeedEntry("Longbow", Tag.BaseGame),
    SeedEntry("Madhous!", Tag.BaseGame),
    SeedEntry("Hammer Buster", Tag.BaseGame),
    SeedEntry("Veruc", Tag.BaseGame),
    SeedEntry("KerBlaster", Tag.BaseGame),
    SeedEntry("Shredifier", Tag.BaseGame),
    SeedEntry("Captain Blade's Otto Idol", Tag.PiratesBooty),
    SeedEntry("Blood of the Seraphs", Tag.PiratesBooty),
    SeedEntry("Midnight Star", Tag.PiratesBooty),
    SeedEntry("Evolution", Tag.PiratesBooty),
    SeedEntry("Manly Man Shield", Tag.PiratesBooty),
    SeedEntry("Greed", Tag.PiratesBooty),
    SeedEntry("12 Pounder", Tag.PiratesBooty),
    SeedEntry("Little Evie", Tag.PiratesBooty),
    SeedEntry("Stinkpot", Tag.PiratesBooty),
    SeedEntry("Devastator", Tag.PiratesBooty),
    SeedEntry("Tattler", Tag.PiratesBooty),
    SeedEntry("Retcher", Tag.PiratesBooty),
    SeedEntry("Actualizer", Tag.PiratesBooty),
    SeedEntry("Seraphim", Tag.PiratesBooty),
    SeedEntry("Patriot", Tag.PiratesBooty),
    SeedEntry("Ahab", Tag.PiratesBooty),
    SeedEntry("Rapier", Tag.PiratesBooty),
    SeedEntry("Jolly Roger", Tag.PiratesBooty),
    SeedEntry("Orphan Maker", Tag.PiratesBooty),
    SeedEntry("Sand Hawk", Tag.PiratesBooty),
    SeedEntry("Pimpernel", Tag.PiratesBooty),
    SeedEntry("Big Boom Blaster", Tag.CampaignOfCarnage),
    SeedEntry("Hoplite", Tag.CampaignOfCarnage),
    SeedEntry("Pun-chee", Tag.CampaignOfCarnage),
    SeedEntry("Sponge", Tag.CampaignOfCarnage),
    SeedEntry("Crossfire", Tag.CampaignOfCarnage),
    SeedEntry("Meteor Shower", Tag.CampaignOfCarnage),
    SeedEntry("O-Negative", Tag.CampaignOfCarnage),
    SeedEntry("Might of the Seraphs", Tag.CampaignOfCarnage),
    SeedEntry("Slow Hand", Tag.CampaignOfCarnage),
    SeedEntry("Pocket Rocket", Tag.CampaignOfCarnage),
    SeedEntry("Cobra", Tag.CampaignOfCarnage),
    SeedEntry("Boom Puppy", Tag.CampaignOfCarnage),
    SeedEntry("Kitten", Tag.CampaignOfCarnage),
    SeedEntry("Breath of the Seraphs", Tag.HammerlocksHunt),
    SeedEntry("The Rough Rider", Tag.HammerlocksHunt),
    SeedEntry("Hawk Eye", Tag.HammerlocksHunt),
    SeedEntry("Infection", Tag.HammerlocksHunt),
    SeedEntry("Interfacer", Tag.HammerlocksHunt),
    SeedEntry("Lead Storm", Tag.HammerlocksHunt),
    SeedEntry("Rex", Tag.HammerlocksHunt),
    SeedEntry("Hydra", Tag.HammerlocksHunt),
    SeedEntry("Damned Cowboy", Tag.HammerlocksHunt),
    SeedEntry("Elephant Gun", Tag.HammerlocksHunt),
    SeedEntry("CHOPPER", Tag.HammerlocksHunt),
    SeedEntry("Yellow Jacket", Tag.HammerlocksHunt),
    SeedEntry("Twister", Tag.HammerlocksHunt),
    SeedEntry("Ogre", Tag.DragonKeep),
    SeedEntry("Grog Nozzle", Tag.DragonKeep),
    SeedEntry("Crit", Tag.DragonKeep),
    SeedEntry("Omen", Tag.DragonKeep),
    SeedEntry("Stinger", Tag.DragonKeep),
    SeedEntry("Seeker", Tag.DragonKeep),
    SeedEntry("Florentine", Tag.DragonKeep),
    SeedEntry("SWORDSPLOSION!!!", Tag.DragonKeep),
    SeedEntry("Orc", Tag.DragonKeep),
    SeedEntry("Mysterious Amulet", Tag.DragonKeep),
    SeedEntry("Shadow of the Seraphs", Tag.DragonKeep),
    SeedEntry("Chain Lightning", Tag.DragonKeep),
    SeedEntry("Fireball", Tag.DragonKeep),
    SeedEntry("Fire Storm", Tag.DragonKeep),
    SeedEntry("Lightning Bolt", Tag.DragonKeep),
    SeedEntry("Blue Magic Missile", Tag.DragonKeep),
    SeedEntry("Purple Magic Missile", Tag.DragonKeep),
    SeedEntry("Blockade", Tag.DragonKeep),
    SeedEntry("Antagonist", Tag.DragonKeep),
    SeedEntry("Hector's Paradise", Tag.FightForSanctuary),
    SeedEntry("Unicornsplosion", Tag.FightForSanctuary),
    SeedEntry("M2828 Thumpson", Tag.FightForSanctuary),
    SeedEntry("Nirvana", Tag.FightForSanctuary),
    SeedEntry("Hot Mama", Tag.FightForSanctuary),
    SeedEntry("Infection Cleaner", Tag.FightForSanctuary),
    SeedEntry("Amigo Sincero", Tag.FightForSanctuary),
    SeedEntry("Overcompensator", Tag.FightForSanctuary),
    SeedEntry("Peak Opener", Tag.FightForSanctuary),
    SeedEntry("Toothpick", Tag.FightForSanctuary),
    SeedEntry("World Burn", Tag.FightForSanctuary),
    SeedEntry("Winter is Over", Tag.FightForSanctuary),
    SeedEntry("Hard Carry", Tag.FightForSanctuary),
    SeedEntry("Mouthwash", Tag.FightForSanctuary),
    SeedEntry("Antifection", Tag.FightForSanctuary),
    SeedEntry("The Electric Chair", Tag.FightForSanctuary),
    SeedEntry("Retainer", Tag.FightForSanctuary),
    SeedEntry("Easy Mode", Tag.FightForSanctuary),
    SeedEntry("Heart of the Ancients", Tag.UVHMPack),
    SeedEntry("Bone of the Ancients", Tag.UVHMPack),
    SeedEntry("Skin of the Ancients", Tag.UVHMPack),
    SeedEntry("Blood of the Ancients", Tag.UVHMPack),
    SeedEntry("Unforgiven", Tag.UVHMPack),
    SeedEntry("Stalker", Tag.UVHMPack),
    SeedEntry("Sawbar", Tag.UVHMPack),
    SeedEntry("Bearcat", Tag.UVHMPack),
    SeedEntry("Avenger", Tag.UVHMPack),
    SeedEntry("Butcher", Tag.UVHMPack),
    SeedEntry("Storm", Tag.UVHMPack),
    SeedEntry("Tunguska", Tag.UVHMPack),
    SeedEntry("Carnage", Tag.DigistructPeak),
    SeedEntry("Wanderlust", Tag.DigistructPeak),
    SeedEntry("Godfinger", Tag.DigistructPeak),
    SeedEntry("Bekah", Tag.DigistructPeak),
)


Locations = (
    SeedEntry("Enemy: Knuckle Dragger", Tag.BaseGame|Tag.UniqueEnemy),
    SeedEntry("Mission: This Town Ain't Big Enough", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Mission: Shielded Favors", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Mission: Bad Hair Day (Turn in Hammerlock)", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Mission: Bad Hair Day (Turn in Claptrap)", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Mission: Symbiosis", Tag.BaseGame|Tag.LongMission),
    SeedEntry("Enemy: Midgemong", Tag.BaseGame|Tag.SlowEnemy),
    SeedEntry("Mission: Handsome Jack Here!", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Enemy: Boom", Tag.BaseGame|Tag.UniqueEnemy),
    SeedEntry("Enemy: Bewm", Tag.BaseGame|Tag.UniqueEnemy),
    SeedEntry("Enemy: Captain Flynt", Tag.BaseGame|Tag.SlowEnemy),
    SeedEntry("Enemy: Savage Lee", Tag.BaseGame|Tag.UniqueEnemy),
    SeedEntry("Other: Michael Mamaril", Tag.BaseGame|Tag.Miscellaneous|Tag.Freebie),
    SeedEntry("Other: Tip Moxxi", Tag.BaseGame|Tag.Miscellaneous|Tag.Freebie),
    SeedEntry("Mission: Claptrap's Secret Stash", Tag.BaseGame|Tag.ShortMission|Tag.Freebie),
    SeedEntry("Mission: Do No Harm", Tag.BaseGame|Tag.ShortMission|Tag.Freebie),
    SeedEntry("Mission: Rock, Paper, Genocide: Fire Weapons!", Tag.BaseGame|Tag.ShortMission|Tag.Freebie),
    SeedEntry("Mission: Rock, Paper, Genocide: Shock Weapons!", Tag.BaseGame|Tag.ShortMission|Tag.Freebie),
    SeedEntry("Mission: Rock, Paper, Genocide: Corrosive Weapons!", Tag.BaseGame|Tag.ShortMission|Tag.Freebie),
    SeedEntry("Mission: Rock, Paper, Genocide: Slag Weapons!", Tag.BaseGame|Tag.ShortMission|Tag.Freebie),
    SeedEntry("Mission: The Name Game", Tag.BaseGame|Tag.LongMission),
    SeedEntry("Mission: Assassinate the Assassins", Tag.BaseGame|Tag.LongMission),
    SeedEntry("Enemy: Assassin Wot", Tag.BaseGame|Tag.UniqueEnemy),
    SeedEntry("Enemy: Assassin Oney", Tag.BaseGame|Tag.UniqueEnemy),
    SeedEntry("Enemy: Assassin Reeth", Tag.BaseGame|Tag.SlowEnemy),
    SeedEntry("Enemy: Assassin Rouf", Tag.BaseGame|Tag.SlowEnemy),
    SeedEntry("Mission: Medical Mystery", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Enemy: Doc Mercy", Tag.BaseGame|Tag.UniqueEnemy),
    SeedEntry("Mission: Medical Mystery: X-Com-municate", Tag.BaseGame|Tag.LongMission),
    SeedEntry("Mission: No Vacancy", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Mission: Neither Rain nor Sleet nor Skags", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Enemy: Loot Midget", Tag.BaseGame|Tag.VeryRareEnemy),
    SeedEntry("Enemy: Chubby/Tubby", Tag.BaseGame|Tag.VeryRareEnemy),
    SeedEntry("Enemy: GOD-liath", Tag.BaseGame|Tag.EvolvedEnemy),
    SeedEntry("Other: Frostburn Canyon Cave Pool", Tag.BaseGame|Tag.Miscellaneous),
    SeedEntry("Mission: Cult Following: Eternal Flame", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Mission: Cult Following: False Idols", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Enemy: Scorch", Tag.BaseGame|Tag.UniqueEnemy),
    SeedEntry("Mission: Cult Following: Lighting the Match", Tag.BaseGame|Tag.LongMission),
    SeedEntry("Mission: Cult Following: The Enkindling", Tag.BaseGame|Tag.LongMission),
    SeedEntry("Enemy: Incinerator Clayton", Tag.BaseGame|Tag.SlowEnemy),
    SeedEntry("Mission: In Memoriam", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Enemy: Boll", Tag.BaseGame|Tag.UniqueEnemy),
    SeedEntry("Other: What's In The Box?", Tag.BaseGame|Tag.Miscellaneous|Tag.Freebie),
    SeedEntry("Enemy: The Black Queen", Tag.BaseGame|Tag.SlowEnemy|Tag.RareEnemy),
    SeedEntry("Mission: Too Close For Missiles", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Enemy: Shirtless Man", Tag.BaseGame|Tag.ShortMission|Tag.UniqueEnemy|Tag.MissionLocation),
    SeedEntry("Mission: Positive Self Image", Tag.BaseGame|Tag.VehicleMission),
    SeedEntry("Enemy: Bad Maw", Tag.BaseGame|Tag.UniqueEnemy),
    SeedEntry("Enemy: Mad Mike", Tag.BaseGame|Tag.SlowEnemy),
    SeedEntry("Mission: Out of Body Experience (Turn in Marcus)", Tag.BaseGame|Tag.LongMission),
    SeedEntry("Mission: Out of Body Experience (Turn in Dr. Zed)", Tag.BaseGame|Tag.LongMission),
    SeedEntry("Enemy: Loader #1340", Tag.BaseGame|Tag.LongMission|Tag.UniqueEnemy|Tag.MissionLocation),
    SeedEntry("Mission: Splinter Group", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Enemy: Lee", Tag.BaseGame|Tag.UniqueEnemy),
    SeedEntry("Enemy: Dan", Tag.BaseGame|Tag.UniqueEnemy),
    SeedEntry("Enemy: Ralph", Tag.BaseGame|Tag.UniqueEnemy),
    SeedEntry("Enemy: Mick", Tag.BaseGame|Tag.UniqueEnemy),
    SeedEntry("Enemy: Flinter", Tag.BaseGame|Tag.UniqueEnemy),
    SeedEntry("Other: Tundra Express Snowman Head", Tag.BaseGame|Tag.Miscellaneous|Tag.Freebie),
    SeedEntry("Enemy: Ultimate Badass Varkid", Tag.BaseGame|Tag.VeryRareEnemy|Tag.EvolvedEnemy),
    SeedEntry("Enemy: Vermivorous the Invincible", Tag.BaseGame|Tag.VeryRareEnemy|Tag.Raid|Tag.EvolvedEnemy),
    SeedEntry("Mission: Mighty Morphin'", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Enemy: Mutated Badass Varkid", Tag.BaseGame|Tag.ShortMission|Tag.UniqueEnemy|Tag.MissionLocation),
    SeedEntry("Mission: No Hard Feelings", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Mission: You Are Cordially Invited: Party Prep", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Enemy: Madame Von Bartlesby", Tag.BaseGame|Tag.UniqueEnemy),
    SeedEntry("Mission: You Are Cordially Invited: RSVP", Tag.BaseGame|Tag.LongMission),
    SeedEntry("Enemy: Flesh-Stick", Tag.BaseGame|Tag.LongMission|Tag.UniqueEnemy|Tag.MissionLocation),
    SeedEntry("Mission: You Are Cordially Invited: Tea Party", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Mission: Mine, All Mine", Tag.BaseGame|Tag.LongMission),
    SeedEntry("Enemy: Prospector Zeke", Tag.BaseGame|Tag.SlowEnemy),
    SeedEntry("Mission: The Pretty Good Train Robbery", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Enemy: Wilhelm", Tag.BaseGame|Tag.UniqueEnemy),
    SeedEntry("Mission: The Good, the Bad, and the Mordecai", Tag.BaseGame|Tag.LongMission),
    SeedEntry("Enemy: Mobley", Tag.BaseGame|Tag.SlowEnemy),
    SeedEntry("Enemy: Gettle", Tag.BaseGame|Tag.SlowEnemy),
    SeedEntry("Enemy: Badass Creeper", Tag.BaseGame|Tag.SlowEnemy),
    SeedEntry("Mission: The Ice Man Cometh", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Mission: Bandit Slaughter: Round 1", Tag.BaseGame|Tag.Slaughter),
    SeedEntry("Mission: Bandit Slaughter: Round 2", Tag.BaseGame|Tag.Slaughter),
    SeedEntry("Mission: Bandit Slaughter: Round 3", Tag.BaseGame|Tag.LongMission|Tag.Slaughter),
    SeedEntry("Mission: Bandit Slaughter: Round 4", Tag.BaseGame|Tag.LongMission|Tag.Slaughter),
    SeedEntry("Mission: Bandit Slaughter: Round 5", Tag.BaseGame|Tag.VeryLongMission|Tag.Slaughter),
    SeedEntry("Mission: Won't Get Fooled Again", Tag.BaseGame|Tag.ShortMission|Tag.Freebie),
    SeedEntry("Enemy: Barlo Gutter", Tag.BaseGame|Tag.ShortMission|Tag.UniqueEnemy|Tag.MissionLocation|Tag.Freebie),
    SeedEntry("Mission: Claptrap's Birthday Bash!", Tag.BaseGame|Tag.ShortMission|Tag.Freebie),
    SeedEntry("Mission: Slap-Happy", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Enemy: Old Slappy", Tag.BaseGame|Tag.UniqueEnemy),
    SeedEntry("Mission: Hidden Journals", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Mission: Torture Chairs", Tag.BaseGame|Tag.ShortMission|Tag.Freebie),
    SeedEntry("Mission: Arms Dealing", Tag.BaseGame|Tag.VehicleMission),
    SeedEntry("Mission: Stalker of Stalkers", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Mission: Best Mother's Day Ever", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Enemy: Henry", Tag.BaseGame|Tag.UniqueEnemy),
    SeedEntry("Mission: The Overlooked: Medicine Man", Tag.BaseGame|Tag.LongMission),
    SeedEntry("Enemy: Requisition Officer", Tag.BaseGame|Tag.LongMission|Tag.UniqueEnemy|Tag.MissionLocation),
    SeedEntry("Mission: The Overlooked: Shields Up", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Mission: The Overlooked: This Is Only a Test", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Mission: Clan War: Starting the War", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Mission: Clan War: First Place", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Mission: Clan War: Reach the Dead Drop", Tag.BaseGame|Tag.ShortMission|Tag.Freebie),
    SeedEntry("Mission: Clan War: End of the Rainbow", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Enemy: Bagman", Tag.BaseGame|Tag.ShortMission|Tag.UniqueEnemy|Tag.MissionLocation),
    SeedEntry("Mission: Clan War: Trailer Trashing", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Mission: Clan War: Wakey Wakey", Tag.BaseGame|Tag.ShortMission|Tag.Freebie),
    SeedEntry("Mission: Clan War: Zafords vs. Hodunks (Kill Hodunks)", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Enemy: Tector Hodunk", Tag.BaseGame|Tag.UniqueEnemy),
    SeedEntry("Mission: Clan War: Zafords vs. Hodunks (Kill Zafords)", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Enemy: Mick Zaford", Tag.BaseGame|Tag.UniqueEnemy),
    SeedEntry("Mission: Safe and Sound (Turn in Marcus)", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Mission: Safe and Sound (Turn in Moxxi)", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Enemy: Blue", Tag.BaseGame|Tag.UniqueEnemy),
    SeedEntry("Mission: Minecart Mischief", Tag.BaseGame|Tag.LongMission),
    SeedEntry("Mission: Perfectly Peaceful", Tag.BaseGame|Tag.LongMission),
    SeedEntry("Mission: The Cold Shoulder", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Enemy: Laney White", Tag.BaseGame|Tag.UniqueEnemy),
    SeedEntry("Mission: Swallowed Whole", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Enemy: Sinkhole", Tag.BaseGame|Tag.SlowEnemy),
    SeedEntry("Enemy: Shorty", Tag.BaseGame|Tag.SlowEnemy),
    SeedEntry("Mission: Note for Self-Person", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Enemy: Smash-Head", Tag.BaseGame|Tag.SlowEnemy),
    SeedEntry("Enemy: Rakkman", Tag.BaseGame|Tag.SlowEnemy),
    SeedEntry("Mission: Doctor's Orders", Tag.BaseGame|Tag.LongMission),
    SeedEntry("Enemy: Loot Midget (Doctor's Orders)", Tag.BaseGame|Tag.LongMission|Tag.UniqueEnemy|Tag.MissionLocation),
    SeedEntry("Enemy: Tumbaa", Tag.BaseGame|Tag.RareEnemy),
    SeedEntry("Enemy: Pimon", Tag.BaseGame|Tag.RareEnemy),
    SeedEntry("Mission: Creature Slaughter: Round 1", Tag.BaseGame|Tag.Slaughter),
    SeedEntry("Mission: Creature Slaughter: Round 2", Tag.BaseGame|Tag.Slaughter),
    SeedEntry("Mission: Creature Slaughter: Round 3", Tag.BaseGame|Tag.LongMission|Tag.Slaughter),
    SeedEntry("Mission: Creature Slaughter: Round 4", Tag.BaseGame|Tag.LongMission|Tag.Slaughter),
    SeedEntry("Mission: Creature Slaughter: Round 5", Tag.BaseGame|Tag.VeryLongMission|Tag.Slaughter),
    SeedEntry("Enemy: Son of Mothrakk", Tag.BaseGame|Tag.SlowEnemy),
    SeedEntry("Mission: Animal Rights", Tag.BaseGame|Tag.LongMission),
    SeedEntry("Mission: Rakkaholics Anonymous (Turn in Mordecai)", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Mission: Rakkaholics Anonymous (Turn in Moxxi)", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Mission: Poetic License", Tag.BaseGame|Tag.ShortMission|Tag.Freebie),
    SeedEntry("Enemy: Daisy", Tag.BaseGame|Tag.ShortMission|Tag.UniqueEnemy|Tag.MissionLocation|Tag.Freebie),
    SeedEntry("Enemy: Muscles", Tag.BaseGame|Tag.VeryRareEnemy),
    SeedEntry("Mission: Shoot This Guy in the Face", Tag.BaseGame|Tag.ShortMission|Tag.Freebie),
    SeedEntry("Mission: Rocko's Modern Strife", Tag.BaseGame|Tag.ShortMission|Tag.Freebie),
    SeedEntry("Mission: Defend Slab Tower", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Mission: Hyperion Contract #873", Tag.BaseGame|Tag.LongMission),
    SeedEntry("Mission: The Bane", Tag.BaseGame|Tag.LongMission),
    SeedEntry("Enemy: McNally", Tag.BaseGame|Tag.UniqueEnemy),
    SeedEntry("Mission: 3:10 to Kaboom", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Enemy: Mad Dog", Tag.BaseGame|Tag.SlowEnemy),
    SeedEntry("Mission: Breaking the Bank", Tag.BaseGame|Tag.LongMission),
    SeedEntry("Mission: Showdown", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Enemy: The Sheriff of Lynchwood", Tag.BaseGame|Tag.UniqueEnemy),
    SeedEntry("Enemy: Deputy Winger", Tag.BaseGame|Tag.UniqueEnemy),
    SeedEntry("Mission: Animal Rescue: Medicine", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Mission: Animal Rescue: Food", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Mission: Animal Rescue: Shelter", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Mission: Hell Hath No Fury", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Enemy: Foreman Jasper/Rusty", Tag.BaseGame|Tag.UniqueEnemy),
    SeedEntry("Mission: Statuesque", Tag.BaseGame|Tag.LongMission),
    SeedEntry("Enemy: Hacked Overseer", Tag.BaseGame|Tag.LongMission|Tag.UniqueEnemy|Tag.MissionLocation),
    SeedEntry("Mission: Home Movies", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Mission: Written by the Victor", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Enemy: BNK-3R", Tag.BaseGame|Tag.SlowEnemy),
    SeedEntry("Mission: Bearer of Bad News", Tag.BaseGame|Tag.ShortMission|Tag.Freebie),
    SeedEntry("Mission: BFFs", Tag.BaseGame|Tag.ShortMission|Tag.Freebie),
    SeedEntry("Enemy: Jim Kepler", Tag.BaseGame|Tag.ShortMission|Tag.UniqueEnemy|Tag.MissionLocation|Tag.Freebie),
    SeedEntry("Mission: Demon Hunter", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Enemy: Dukino's Mom", Tag.BaseGame|Tag.SlowEnemy),
    SeedEntry("Mission: Monster Mash (Part 1)", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Mission: Monster Mash (Part 2)", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Other: Geary's Unbreakable Gear", Tag.BaseGame|Tag.VeryLongMission|Tag.Miscellaneous),
    SeedEntry("Enemy: Geary", Tag.BaseGame|Tag.SlowEnemy),
    SeedEntry("Enemy: Donkey Mong", Tag.BaseGame|Tag.RareEnemy),
    SeedEntry("Enemy: King Mong", Tag.BaseGame|Tag.RareEnemy),
    SeedEntry("Mission: Kill Yourself (Do it)", Tag.BaseGame|Tag.ShortMission|Tag.Freebie),
    SeedEntry("Mission: Kill Yourself (Don't do it)", Tag.BaseGame|Tag.ShortMission|Tag.Freebie),
    SeedEntry("Mission: Customer Service", Tag.BaseGame|Tag.VehicleMission),
    SeedEntry("Mission: To Grandmother's House We Go", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Mission: A Real Boy: Clothes Make the Man", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Mission: A Real Boy: Face Time", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Mission: A Real Boy: Human", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Mission: Hyperion Slaughter: Round 1", Tag.BaseGame|Tag.Slaughter),
    SeedEntry("Mission: Hyperion Slaughter: Round 2", Tag.BaseGame|Tag.Slaughter),
    SeedEntry("Mission: Hyperion Slaughter: Round 3", Tag.BaseGame|Tag.LongMission|Tag.Slaughter),
    SeedEntry("Mission: Hyperion Slaughter: Round 4", Tag.BaseGame|Tag.LongMission|Tag.Slaughter),
    SeedEntry("Mission: Hyperion Slaughter: Round 5", Tag.BaseGame|Tag.VeryLongMission|Tag.Slaughter),
    SeedEntry("Mission: The Lost Treasure", Tag.BaseGame|Tag.VeryLongMission),
    SeedEntry("Mission: The Great Escape", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Mission: The Chosen One", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Mission: Capture the Flags", Tag.BaseGame|Tag.VeryLongMission),
    SeedEntry("Enemy: Mortar", Tag.BaseGame|Tag.UniqueEnemy),
    SeedEntry("Mission: Monster Mash (Part 3)", Tag.BaseGame|Tag.LongMission),
    SeedEntry("Enemy: Spycho", Tag.BaseGame|Tag.SlowEnemy),
    SeedEntry("Mission: This Just In", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Enemy: Hunter Hellquist", Tag.BaseGame|Tag.UniqueEnemy),
    SeedEntry("Mission: Uncle Teddy (Turn in Una)", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Mission: Uncle Teddy (Turn in Hyperion)", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Mission: Get to Know Jack", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Mission: Hungry Like the Skag", Tag.BaseGame|Tag.ShortMission),
    SeedEntry("Enemy: Bone Head 2.0", Tag.BaseGame|Tag.UniqueEnemy),
    SeedEntry("Enemy: Saturn", Tag.BaseGame|Tag.SlowEnemy),
    SeedEntry("Enemy: The Warrior", Tag.BaseGame|Tag.SlowEnemy),
    SeedEntry("Mission: You. Will. Die. (Seriously.)", Tag.BaseGame|Tag.ShortMission|Tag.Raid),
    SeedEntry("Enemy: Terramorphous the Invincible", Tag.BaseGame|Tag.UniqueEnemy|Tag.Raid),
    SeedEntry("Other: Oasis Seraph Vendor", Tag.PiratesBooty|Tag.Vendor),
    SeedEntry("Mission: Message in a Bottle (Oasis)", Tag.PiratesBooty|Tag.ShortMission|Tag.Freebie),
    SeedEntry("Mission: Man's Best Friend", Tag.PiratesBooty|Tag.ShortMission),
    SeedEntry("Enemy: Tinkles", Tag.PiratesBooty|Tag.UniqueEnemy),
    SeedEntry("Mission: Burying the Past", Tag.PiratesBooty|Tag.ShortMission),
    SeedEntry("Mission: Fire Water", Tag.PiratesBooty|Tag.ShortMission),
    SeedEntry("Mission: Giving Jocko A Leg Up", Tag.PiratesBooty|Tag.ShortMission),
    SeedEntry("Mission: Wingman", Tag.PiratesBooty|Tag.ShortMission),
    SeedEntry("Mission: Smells Like Victory", Tag.PiratesBooty|Tag.ShortMission),
    SeedEntry("Mission: Declaration Against Independents", Tag.PiratesBooty|Tag.VehicleMission),
    SeedEntry("Mission: Ye Scurvy Dogs", Tag.PiratesBooty|Tag.ShortMission),
    SeedEntry("Mission: Message in a Bottle (Wurmwater)", Tag.PiratesBooty|Tag.ShortMission),
    SeedEntry("Mission: Grendel", Tag.PiratesBooty|Tag.ShortMission),
    SeedEntry("Enemy: Grendel", Tag.PiratesBooty|Tag.UniqueEnemy),
    SeedEntry("Mission: Message in a Bottle (Hayter's Folly)", Tag.PiratesBooty|Tag.ShortMission),
    SeedEntry("Enemy: The Big Sleep", Tag.PiratesBooty|Tag.SlowEnemy),
    SeedEntry("Enemy: Sandman", Tag.PiratesBooty|Tag.SlowEnemy),
    SeedEntry("Mission: Just Desserts for Desert Deserters", Tag.PiratesBooty|Tag.LongMission),
    SeedEntry("Enemy: Benny the Booster", Tag.PiratesBooty|Tag.UniqueEnemy),
    SeedEntry("Enemy: Deckhand", Tag.PiratesBooty|Tag.SlowEnemy),
    SeedEntry("Enemy: Toothless Terry", Tag.PiratesBooty|Tag.LongMission|Tag.UniqueEnemy|Tag.MissionLocation),
    SeedEntry("Mission: Message in a Bottle (The Rustyards)", Tag.PiratesBooty|Tag.ShortMission),
    SeedEntry("Mission: I Know It When I See It", Tag.PiratesBooty|Tag.ShortMission),
    SeedEntry("Enemy: P3RV-E", Tag.PiratesBooty|Tag.SlowEnemy),
    SeedEntry("Mission: Don't Copy That Floppy", Tag.PiratesBooty|Tag.ShortMission),
    SeedEntry("Enemy: H3RL-E", Tag.PiratesBooty|Tag.SlowEnemy),
    SeedEntry("Mission: Faster Than the Speed of Love", Tag.PiratesBooty|Tag.VehicleMission|Tag.Freebie),
    SeedEntry("Mission: Catch-A-Ride, and Also Tetanus", Tag.PiratesBooty|Tag.ShortMission),
    SeedEntry("Mission: Freedom of Speech", Tag.PiratesBooty|Tag.ShortMission),
    SeedEntry("Enemy: DJ Tanner", Tag.PiratesBooty|Tag.SlowEnemy),
    SeedEntry("Enemy: Mr. Bubbles", Tag.PiratesBooty|Tag.VeryRareEnemy),
    SeedEntry("Enemy: Lil' Sis", Tag.PiratesBooty|Tag.VeryRareEnemy),
    SeedEntry("Mission: Message In A Bottle (Magnys Lighthouse)", Tag.PiratesBooty|Tag.ShortMission),
    SeedEntry("Mission: Treasure of the Sands", Tag.PiratesBooty|Tag.VeryLongMission),
    SeedEntry("Enemy: Lieutenant White", Tag.PiratesBooty|Tag.VeryLongMission|Tag.UniqueEnemy|Tag.MissionLocation),
    SeedEntry("Enemy: Lieutenant Hoffman", Tag.PiratesBooty|Tag.VeryLongMission|Tag.UniqueEnemy|Tag.MissionLocation),
    SeedEntry("Enemy: Captain Scarlett", Tag.PiratesBooty|Tag.VeryLongMission|Tag.UniqueEnemy|Tag.MissionLocation),
    SeedEntry("Enemy: Leviathan", Tag.PiratesBooty|Tag.VeryLongMission|Tag.UniqueEnemy|Tag.MissionLocation),
    SeedEntry("Mission: Hyperius the Invincible", Tag.PiratesBooty|Tag.ShortMission|Tag.Raid),
    SeedEntry("Enemy: Hyperius the Invincible", Tag.PiratesBooty|Tag.UniqueEnemy|Tag.Raid),
    SeedEntry("Mission: Master Gee the Invincible", Tag.PiratesBooty|Tag.ShortMission|Tag.Raid),
    SeedEntry("Enemy: Master Gee the Invincible", Tag.PiratesBooty|Tag.UniqueEnemy|Tag.Raid),
    SeedEntry("Other: Badass Crater Seraph Vendor", Tag.CampaignOfCarnage|Tag.Vendor),
    SeedEntry("Other: Torgue Vendor", Tag.CampaignOfCarnage|Tag.Vendor),
    SeedEntry("Other: Torgue Arena Provided Loot", Tag.CampaignOfCarnage|Tag.Miscellaneous|Tag.Freebie),
    SeedEntry("Enemy: Gladiator Goliath", Tag.CampaignOfCarnage|Tag.Slaughter|Tag.UniqueEnemy|Tag.MissionLocation),
    SeedEntry("Mission: Tier 2 Battle: Appetite for Destruction", Tag.CampaignOfCarnage|Tag.Slaughter),
    SeedEntry("Mission: Tier 3 Battle: Appetite for Destruction", Tag.CampaignOfCarnage|Tag.Slaughter),
    SeedEntry("Enemy: Pete's Burner", Tag.CampaignOfCarnage|Tag.MobFarm),
    SeedEntry("Mission: Tier 2 Battle: Bar Room Blitz", Tag.CampaignOfCarnage|Tag.Slaughter),
    SeedEntry("Mission: Tier 3 Battle: Bar Room Blitz", Tag.CampaignOfCarnage|Tag.Slaughter),
    SeedEntry("Mission: Totally Recall", Tag.CampaignOfCarnage|Tag.ShortMission),
    SeedEntry("Mission: Mother-Lover (Turn in Scooter)", Tag.CampaignOfCarnage|Tag.ShortMission),
    SeedEntry("Mission: Mother-Lover (Turn in Moxxi)", Tag.CampaignOfCarnage|Tag.ShortMission),
    SeedEntry("Enemy: Hamhock the Ham", Tag.CampaignOfCarnage|Tag.ShortMission|Tag.UniqueEnemy|Tag.MissionLocation),
    SeedEntry("Mission: Tier 2 Battle: The Death Race", Tag.CampaignOfCarnage|Tag.VehicleMission|Tag.Freebie),
    SeedEntry("Mission: Tier 3 Battle: The Death Race", Tag.CampaignOfCarnage|Tag.VehicleMission|Tag.Freebie),
    SeedEntry("Mission: Number One Fan", Tag.CampaignOfCarnage|Tag.ShortMission),
    SeedEntry("Enemy: Sully the Stabber", Tag.CampaignOfCarnage|Tag.ShortMission|Tag.UniqueEnemy|Tag.MissionLocation),
    SeedEntry("Mission: Walking the Dog", Tag.CampaignOfCarnage|Tag.LongMission),
    SeedEntry("Enemy: Enrique", Tag.CampaignOfCarnage|Tag.LongMission|Tag.UniqueEnemy|Tag.MissionLocation),
    SeedEntry("Mission: Monster Hunter", Tag.CampaignOfCarnage|Tag.ShortMission),
    SeedEntry("Enemy: The Monster Truck", Tag.CampaignOfCarnage|Tag.ShortMission|Tag.UniqueEnemy|Tag.MissionLocation),
    SeedEntry("Mission: Gas Guzzlers (Turn in Hammerlock)", Tag.CampaignOfCarnage|Tag.LongMission),
    SeedEntry("Mission: Gas Guzzlers (Turn in Scooter)", Tag.CampaignOfCarnage|Tag.LongMission),
    SeedEntry("Enemy: Chubby Rakk (Gas Guzzlers)", Tag.CampaignOfCarnage|Tag.LongMission|Tag.UniqueEnemy|Tag.MissionLocation),
    SeedEntry("Mission: Matter Of Taste", Tag.CampaignOfCarnage|Tag.LongMission),
    SeedEntry("Enemy: BuffGamer G", Tag.CampaignOfCarnage|Tag.LongMission|Tag.UniqueEnemy|Tag.MissionLocation),
    SeedEntry("Enemy: Game Critic Extraordinaire", Tag.CampaignOfCarnage|Tag.LongMission|Tag.UniqueEnemy|Tag.MissionLocation),
    SeedEntry("Mission: Everybody Wants to be Wanted", Tag.CampaignOfCarnage|Tag.ShortMission),
    SeedEntry("Mission: Interview with a Vault Hunter", Tag.CampaignOfCarnage|Tag.ShortMission),
    SeedEntry("Enemy: Motor Momma", Tag.CampaignOfCarnage|Tag.SlowEnemy),
    SeedEntry("Mission: Tier 2 Battle: Twelve O' Clock High", Tag.CampaignOfCarnage|Tag.Slaughter),
    SeedEntry("Mission: Tier 3 Battle: Twelve O' Clock High", Tag.CampaignOfCarnage|Tag.Slaughter),
    SeedEntry("Mission: My Husband the Skag (Kill Uriah)", Tag.CampaignOfCarnage|Tag.ShortMission),
    SeedEntry("Mission: My Husband the Skag (Spare Uriah)", Tag.CampaignOfCarnage|Tag.ShortMission),
    SeedEntry("Mission: Say That To My Face", Tag.CampaignOfCarnage|Tag.ShortMission),
    SeedEntry("Enemy: Anonymous Troll Face", Tag.CampaignOfCarnage|Tag.ShortMission|Tag.UniqueEnemy|Tag.MissionLocation),
    SeedEntry("Mission: Commercial Appeal", Tag.CampaignOfCarnage|Tag.LongMission),
    SeedEntry("Enemy: Piston/Badassasarus Rex", Tag.CampaignOfCarnage|Tag.SlowEnemy),
    SeedEntry("Mission: Pete the Invincible", Tag.CampaignOfCarnage|Tag.ShortMission|Tag.Raid),
    SeedEntry("Enemy: Pyro Pete the Invincible", Tag.CampaignOfCarnage|Tag.UniqueEnemy|Tag.Raid),
    SeedEntry("Other: Hunter's Grotto Seraph Vendor", Tag.HammerlocksHunt|Tag.Vendor),
    SeedEntry("Enemy: Omnd-Omnd-Ohk", Tag.HammerlocksHunt|Tag.VeryRareEnemy|Tag.EvolvedEnemy),
    SeedEntry("Enemy: Dexiduous the Invincible", Tag.HammerlocksHunt|Tag.UniqueEnemy|Tag.Raid),
    SeedEntry("Mission: I Like My Monsters Rare", Tag.HammerlocksHunt|Tag.VeryLongMission),
    SeedEntry("Mission: Still Just a Borok in a Cage", Tag.HammerlocksHunt|Tag.ShortMission),
    SeedEntry("Enemy: Der Monstrositat", Tag.HammerlocksHunt|Tag.ShortMission|Tag.UniqueEnemy|Tag.MissionLocation),
    SeedEntry("Mission: Egg on Your Face", Tag.HammerlocksHunt|Tag.LongMission|Tag.VehicleMission),
    SeedEntry("Mission: An Acquired Taste", Tag.HammerlocksHunt|Tag.ShortMission),
    SeedEntry("Enemy: Bulstoss", Tag.HammerlocksHunt|Tag.SlowEnemy),
    SeedEntry("Enemy: Arizona", Tag.HammerlocksHunt|Tag.SlowEnemy),
    SeedEntry("Mission: Palling Around", Tag.HammerlocksHunt|Tag.ShortMission),
    SeedEntry("Enemy: The Bulwark", Tag.HammerlocksHunt|Tag.SlowEnemy),
    SeedEntry("Mission: Ol' Pukey", Tag.HammerlocksHunt|Tag.LongMission),
    SeedEntry("Mission: Nakayama-rama", Tag.HammerlocksHunt|Tag.LongMission),
    SeedEntry("Mission: The Rakk Dahlia Murder", Tag.HammerlocksHunt|Tag.ShortMission),
    SeedEntry("Enemy: Rakkanoth", Tag.HammerlocksHunt|Tag.ShortMission|Tag.UniqueEnemy|Tag.MissionLocation),
    SeedEntry("Mission: Urine, You're Out", Tag.HammerlocksHunt|Tag.VeryLongMission),
    SeedEntry("Mission: Follow The Glow", Tag.HammerlocksHunt|Tag.ShortMission),
    SeedEntry("Enemy: Dribbles", Tag.HammerlocksHunt|Tag.UniqueEnemy),
    SeedEntry("Enemy: Woundspike", Tag.HammerlocksHunt|Tag.SlowEnemy),
    SeedEntry("Mission: Big Feet", Tag.HammerlocksHunt|Tag.ShortMission),
    SeedEntry("Enemy: Rouge", Tag.HammerlocksHunt|Tag.SlowEnemy),
    SeedEntry("Mission: Now You See It", Tag.HammerlocksHunt|Tag.LongMission),
    SeedEntry("Enemy: Bloodtail", Tag.HammerlocksHunt|Tag.SlowEnemy),
    SeedEntry("Enemy: Jackenstein", Tag.HammerlocksHunt|Tag.SlowEnemy),
    SeedEntry("Mission: Voracidous the Invincible", Tag.HammerlocksHunt|Tag.ShortMission|Tag.Raid),
    SeedEntry("Enemy: Voracidous the Invincible", Tag.HammerlocksHunt|Tag.UniqueEnemy|Tag.Raid),
    SeedEntry("Enemy: Mister Boney Pants Guy", Tag.DragonKeep|Tag.UniqueEnemy),
    SeedEntry("Other: Mimic Chest", Tag.DragonKeep|Tag.Miscellaneous|Tag.Freebie),
    SeedEntry("Other: Flamerock Refuge Seraph Vendor", Tag.DragonKeep|Tag.Vendor),
    SeedEntry("Mission: Roll Insight", Tag.DragonKeep|Tag.ShortMission|Tag.Freebie),
    SeedEntry("Mission: Fake Geek Guy", Tag.DragonKeep|Tag.ShortMission),
    SeedEntry("Mission: Post-Crumpocalyptic", Tag.DragonKeep|Tag.VeryLongMission),
    SeedEntry("Enemy: Treant", Tag.DragonKeep|Tag.UniqueEnemy),
    SeedEntry("Mission: Ell in Shining Armor (Skimpy Armor)", Tag.DragonKeep|Tag.ShortMission),
    SeedEntry("Mission: Ell in Shining Armor (Bulky Armor)", Tag.DragonKeep|Tag.ShortMission),
    SeedEntry("Enemy: Warlord Grug", Tag.DragonKeep|Tag.UniqueEnemy),
    SeedEntry("Enemy: Duke of Ork", Tag.DragonKeep|Tag.EvolvedEnemy),
    SeedEntry("Mission: Tree Hugger", Tag.DragonKeep|Tag.LongMission),
    SeedEntry("Mission: Critical Fail", Tag.DragonKeep|Tag.ShortMission),
    SeedEntry("Enemy: Arguk the Butcher", Tag.DragonKeep|Tag.ShortMission|Tag.UniqueEnemy|Tag.MissionLocation),
    SeedEntry("Mission: Lost Souls", Tag.DragonKeep|Tag.ShortMission),
    SeedEntry("Enemy: -=nOObkiLLer=-", Tag.DragonKeep|Tag.ShortMission|Tag.UniqueEnemy|Tag.MissionLocation),
    SeedEntry("Mission: MMORPGFPS", Tag.DragonKeep|Tag.LongMission),
    SeedEntry("Enemy: xxDatVaultHuntrxx", Tag.DragonKeep|Tag.LongMission|Tag.UniqueEnemy|Tag.MissionLocation),
    SeedEntry("Enemy: 420_E-Sports_Masta", Tag.DragonKeep|Tag.LongMission|Tag.UniqueEnemy|Tag.MissionLocation),
    SeedEntry("Enemy: [720NoScope]Headshotz", Tag.DragonKeep|Tag.LongMission|Tag.UniqueEnemy|Tag.MissionLocation),
    SeedEntry("Enemy: King Aliah", Tag.DragonKeep|Tag.SlowEnemy),
    SeedEntry("Enemy: King Crono", Tag.DragonKeep|Tag.SlowEnemy),
    SeedEntry("Enemy: King Seth", Tag.DragonKeep|Tag.SlowEnemy),
    SeedEntry("Enemy: King Nazar", Tag.DragonKeep|Tag.SlowEnemy),
    SeedEntry("Mission: The Sword in The Stoner", Tag.DragonKeep|Tag.LongMission),
    SeedEntry("Enemy: Unmotivated Golem", Tag.DragonKeep|Tag.LongMission|Tag.UniqueEnemy|Tag.MissionLocation),
    SeedEntry("Enemy: Warlord Turge", Tag.DragonKeep|Tag.UniqueEnemy),
    SeedEntry("Enemy: Spiderpants", Tag.DragonKeep|Tag.SlowEnemy|Tag.VeryRareEnemy),
    SeedEntry("Enemy: Iron GOD", Tag.DragonKeep|Tag.SlowEnemy|Tag.Raid|Tag.EvolvedEnemy),
    SeedEntry("Mission: The Beard Makes The Man", Tag.DragonKeep|Tag.LongMission),
    SeedEntry("Mission: My Kingdom for a Wand", Tag.DragonKeep|Tag.ShortMission),
    SeedEntry("Enemy: Maxibillion", Tag.DragonKeep|Tag.ShortMission|Tag.UniqueEnemy|Tag.MissionLocation),
    SeedEntry("Enemy: Magical Spider", Tag.DragonKeep|Tag.ShortMission|Tag.UniqueEnemy|Tag.MissionLocation),
    SeedEntry("Enemy: Magical Orc", Tag.DragonKeep|Tag.ShortMission|Tag.UniqueEnemy|Tag.MissionLocation),
    SeedEntry("Mission: The Claptrap's Apprentice", Tag.DragonKeep|Tag.ShortMission),
    SeedEntry("Enemy: Gold Golem", Tag.DragonKeep|Tag.SlowEnemy),
    SeedEntry("Enemy: The Darkness", Tag.DragonKeep|Tag.UniqueEnemy),
    SeedEntry("Mission: Loot Ninja", Tag.DragonKeep|Tag.ShortMission),
    SeedEntry("Enemy: Sir Boil", Tag.DragonKeep|Tag.ShortMission|Tag.UniqueEnemy|Tag.MissionLocation),
    SeedEntry("Enemy: Sir Mash", Tag.DragonKeep|Tag.ShortMission|Tag.UniqueEnemy|Tag.MissionLocation),
    SeedEntry("Enemy: Sir Stew", Tag.DragonKeep|Tag.ShortMission|Tag.UniqueEnemy|Tag.MissionLocation),
    SeedEntry("Enemy: Handsome Dragon", Tag.DragonKeep|Tag.UniqueEnemy),
    SeedEntry("Mission: Winter is a Bloody Business", Tag.DragonKeep|Tag.LongMission),
    SeedEntry("Enemy: Canine", Tag.DragonKeep|Tag.LongMission|Tag.UniqueEnemy|Tag.MissionLocation),
    SeedEntry("Enemy: Molehill", Tag.DragonKeep|Tag.LongMission|Tag.UniqueEnemy|Tag.MissionLocation),
    SeedEntry("Mission: My Dead Brother (Kill Edgar)", Tag.DragonKeep|Tag.LongMission),
    SeedEntry("Enemy: Edgar", Tag.DragonKeep|Tag.LongMission|Tag.UniqueEnemy|Tag.MissionLocation),
    SeedEntry("Mission: My Dead Brother (Kill Simon)", Tag.DragonKeep|Tag.LongMission),
    SeedEntry("Enemy: Simon", Tag.DragonKeep|Tag.LongMission|Tag.UniqueEnemy|Tag.MissionLocation),
    SeedEntry("Enemy: Sorcerer", Tag.DragonKeep|Tag.UniqueEnemy),
    SeedEntry("Enemy: Badass Sorcerer", Tag.DragonKeep|Tag.UniqueEnemy),
    SeedEntry("Enemy: Fire Mage", Tag.DragonKeep|Tag.UniqueEnemy),
    SeedEntry("Enemy: Badass Fire Mage", Tag.DragonKeep|Tag.UniqueEnemy),
    SeedEntry("Mission: The Amulet (Buy Miz's Amulet)", Tag.DragonKeep|Tag.LongMission),
    SeedEntry("Mission: The Amulet (Punch Miz In The Face)", Tag.DragonKeep|Tag.LongMission),
    SeedEntry("Enemy: Necromancer", Tag.DragonKeep|Tag.UniqueEnemy),
    SeedEntry("Enemy: Badass Necromancer", Tag.DragonKeep|Tag.UniqueEnemy),
    SeedEntry("Enemy: Sorcerer's Daughter", Tag.DragonKeep|Tag.SlowEnemy),
    SeedEntry("Enemy: Handsome Sorcerer", Tag.DragonKeep|Tag.SlowEnemy),
    SeedEntry("Mission: Pet Butt Stallion", Tag.DragonKeep|Tag.ShortMission|Tag.Freebie),
    SeedEntry("Mission: Feed Butt Stallion", Tag.DragonKeep|Tag.ShortMission|Tag.Freebie),
    SeedEntry("Other: Butt Stallion Fart", Tag.DragonKeep|Tag.Miscellaneous|Tag.Freebie),
    SeedEntry("Mission: Find Murderlin's Temple", Tag.DragonKeep|Tag.ShortMission|Tag.Freebie),
    SeedEntry("Mission: Magic Slaughter: Round 1", Tag.DragonKeep|Tag.Slaughter),
    SeedEntry("Mission: Magic Slaughter: Round 2", Tag.DragonKeep|Tag.Slaughter),
    SeedEntry("Mission: Magic Slaughter: Round 3", Tag.DragonKeep|Tag.LongMission|Tag.Slaughter),
    SeedEntry("Enemy: Wizard", Tag.DragonKeep|Tag.LongMission|Tag.Slaughter|Tag.RareEnemy|Tag.MissionLocation),
    SeedEntry("Mission: Magic Slaughter: Round 4", Tag.DragonKeep|Tag.LongMission|Tag.Slaughter),
    SeedEntry("Mission: Magic Slaughter: Round 5", Tag.DragonKeep|Tag.VeryLongMission|Tag.Slaughter),
    SeedEntry("Mission: Magic Slaughter: Badass Round", Tag.DragonKeep|Tag.VeryLongMission|Tag.Slaughter),
    SeedEntry("Enemy: Badass Wizard", Tag.DragonKeep|Tag.VeryLongMission|Tag.Slaughter|Tag.RareEnemy|Tag.MissionLocation),
    SeedEntry("Enemy: Warlord Slog", Tag.DragonKeep|Tag.VeryLongMission|Tag.Slaughter|Tag.UniqueEnemy|Tag.MissionLocation),
    SeedEntry("Enemy: King of Orks", Tag.DragonKeep|Tag.VeryLongMission|Tag.Slaughter|Tag.MissionLocation|Tag.EvolvedEnemy),
    SeedEntry("Mission: The Magic of Childhood", Tag.DragonKeep|Tag.LongMission|Tag.Slaughter),
    SeedEntry("Mission: Raiders of the Last Boss", Tag.DragonKeep|Tag.ShortMission|Tag.Raid),
    SeedEntry("Enemy: The Ancient Dragons of Destruction", Tag.DragonKeep|Tag.UniqueEnemy|Tag.Raid),
    SeedEntry("Enemy: Infected Badass Sprout", Tag.FightForSanctuary|Tag.MobFarm),
    SeedEntry("Other: Dahl Abandon Grave", Tag.FightForSanctuary|Tag.Miscellaneous|Tag.Freebie),
    SeedEntry("Enemy: Loot Nest", Tag.FightForSanctuary|Tag.UniqueEnemy),
    SeedEntry("Enemy: New Pandora Soldier", Tag.FightForSanctuary|Tag.MobFarm),
    SeedEntry("Mission: The Oddest Couple", Tag.FightForSanctuary|Tag.ShortMission),
    SeedEntry("Enemy: Pizza-Addicted Skag", Tag.FightForSanctuary|Tag.ShortMission|Tag.UniqueEnemy|Tag.MissionLocation),
    SeedEntry("Mission: Space Cowboy", Tag.FightForSanctuary|Tag.LongMission),
    SeedEntry("Enemy: Loot Midget (Space Cowboy)", Tag.FightForSanctuary|Tag.LongMission|Tag.UniqueEnemy|Tag.MissionLocation),
    SeedEntry("Enemy: Sand Worm", Tag.FightForSanctuary|Tag.MobFarm),
    SeedEntry("Enemy: Ghost", Tag.FightForSanctuary|Tag.UniqueEnemy),
    SeedEntry("Enemy: Bandit Leader (Nomad)", Tag.FightForSanctuary|Tag.LongMission|Tag.UniqueEnemy|Tag.MissionLocation),
    SeedEntry("Enemy: Bandit Leader (Marauder)", Tag.FightForSanctuary|Tag.LongMission|Tag.UniqueEnemy|Tag.MissionLocation),
    SeedEntry("Enemy: Jerry", Tag.FightForSanctuary|Tag.LongMission|Tag.UniqueEnemy|Tag.MissionLocation),
    SeedEntry("Mission: The Hunt is Vaughn", Tag.FightForSanctuary|Tag.ShortMission),
    SeedEntry("Mission: Hypocritical Oath", Tag.FightForSanctuary|Tag.ShortMission),
    SeedEntry("Enemy: Dr. Zed's Experiment", Tag.FightForSanctuary|Tag.ShortMission|Tag.UniqueEnemy|Tag.MissionLocation),
    SeedEntry("Mission: Cadeuceus", Tag.FightForSanctuary|Tag.ShortMission),
    SeedEntry("Mission: The Vaughnguard", Tag.FightForSanctuary|Tag.LongMission),
    SeedEntry("Enemy: Uranus", Tag.FightForSanctuary|Tag.SlowEnemy),
    SeedEntry("Mission: Claptocurrency", Tag.FightForSanctuary|Tag.ShortMission),
    SeedEntry("Enemy: The Dark Web", Tag.FightForSanctuary|Tag.ShortMission|Tag.UniqueEnemy|Tag.MissionLocation),
    SeedEntry("Enemy: Cassius", Tag.FightForSanctuary|Tag.SlowEnemy),
    SeedEntry("Mission: Echoes of the Past", Tag.FightForSanctuary|Tag.ShortMission),
    SeedEntry("Mission: Sirentology", Tag.FightForSanctuary|Tag.LongMission),
    SeedEntry("Mission: My Brittle Pony", Tag.FightForSanctuary|Tag.LongMission),
    SeedEntry("Other: Butt Stallion with Mysterious Amulet", Tag.DragonKeep|Tag.FightForSanctuary|Tag.Miscellaneous|Tag.Freebie),
    SeedEntry("Mission: BFFFs", Tag.FightForSanctuary|Tag.ShortMission),
    SeedEntry("Enemy: Lt. Bolson", Tag.FightForSanctuary|Tag.SlowEnemy),
    SeedEntry("Enemy: Lt. Angvar", Tag.FightForSanctuary|Tag.SlowEnemy),
    SeedEntry("Enemy: Lt. Tetra", Tag.FightForSanctuary|Tag.SlowEnemy),
    SeedEntry("Enemy: Lt. Hoffman", Tag.FightForSanctuary|Tag.SlowEnemy),
    SeedEntry("Mission: Chief Executive Overlord", Tag.FightForSanctuary|Tag.ShortMission|Tag.Freebie),
    SeedEntry("Mission: A Most Cacophonous Lure", Tag.FightForSanctuary|Tag.ShortMission|Tag.Raid),
    SeedEntry("Enemy: Haderax The Invincible", Tag.FightForSanctuary|Tag.UniqueEnemy|Tag.Raid),
    SeedEntry("Mission: The Hunger Pangs", Tag.WattleGobbler|Tag.VeryLongMission),
    SeedEntry("Enemy: The Rat in the Hat", Tag.WattleGobbler|Tag.VeryLongMission|Tag.UniqueEnemy|Tag.MissionLocation),
    SeedEntry("Enemy: Chef Gouda Remsay", Tag.WattleGobbler|Tag.VeryLongMission|Tag.UniqueEnemy|Tag.MissionLocation),
    SeedEntry("Enemy: Chef Brulee", Tag.WattleGobbler|Tag.VeryLongMission|Tag.UniqueEnemy|Tag.MissionLocation),
    SeedEntry("Enemy: Chef Bork Bork", Tag.WattleGobbler|Tag.VeryLongMission|Tag.UniqueEnemy|Tag.MissionLocation),
    SeedEntry("Enemy: Glasspool, Tribute of Wurmwater", Tag.WattleGobbler|Tag.VeryLongMission|Tag.UniqueEnemy|Tag.MissionLocation),
    SeedEntry("Enemy: William, Tribute of Wurmwater", Tag.WattleGobbler|Tag.VeryLongMission|Tag.UniqueEnemy|Tag.MissionLocation),
    SeedEntry("Enemy: Axel, Tribute of Opportunity", Tag.WattleGobbler|Tag.VeryLongMission|Tag.UniqueEnemy|Tag.MissionLocation),
    SeedEntry("Enemy: Rose, Tribute of Opportunity", Tag.WattleGobbler|Tag.VeryLongMission|Tag.UniqueEnemy|Tag.MissionLocation),
    SeedEntry("Enemy: Fiona, Tribute of Sanctuary", Tag.WattleGobbler|Tag.RareEnemy),
    SeedEntry("Enemy: Max, Tribute of Sanctuary", Tag.WattleGobbler|Tag.RareEnemy),
    SeedEntry("Enemy: Strip, Tribute of Southern Shelf", Tag.WattleGobbler|Tag.RareEnemy),
    SeedEntry("Enemy: Flay, Tribute of Southern Shelf", Tag.WattleGobbler|Tag.RareEnemy),
    SeedEntry("Enemy: Fuse, Tribute of Frostburn", Tag.WattleGobbler|Tag.RareEnemy),
    SeedEntry("Enemy: Cynder, Tribute of Frostburn", Tag.WattleGobbler|Tag.RareEnemy),
    SeedEntry("Enemy: Annie, Tribute of Lynchwood", Tag.WattleGobbler|Tag.RareEnemy),
    SeedEntry("Enemy: Garret, Tribute of Lynchwood", Tag.WattleGobbler|Tag.RareEnemy),
    SeedEntry("Enemy: Moretus, Tribute of Sawtooth Cauldron", Tag.WattleGobbler|Tag.RareEnemy),
    SeedEntry("Enemy: Bailly, Tribute of Sawtooth Cauldron", Tag.WattleGobbler|Tag.RareEnemy),
    SeedEntry("Enemy: Ravenous Wattle Gobbler", Tag.WattleGobbler|Tag.SlowEnemy),
    SeedEntry("Mission: Grandma Flexington's Story", Tag.WattleGobbler|Tag.LongMission|Tag.Freebie),
    SeedEntry("Mission: Grandma Flexington's Story: Raid Difficulty", Tag.WattleGobbler|Tag.VeryLongMission|Tag.Raid),
    SeedEntry("Mission: Get Frosty", Tag.MercenaryDay|Tag.VeryLongMission),
    SeedEntry("Enemy: The Abominable Mister Tinder Snowflake", Tag.MercenaryDay|Tag.SlowEnemy),
    SeedEntry("Mission: Special Delivery", Tag.MercenaryDay|Tag.ShortMission),
    SeedEntry("Mission: The Bloody Harvest", Tag.BloodyHarvest|Tag.VeryLongMission),
    SeedEntry("Enemy: Enchanted Skeleton", Tag.BloodyHarvest|Tag.VeryRareEnemy),
    SeedEntry("Enemy: Sully the Blacksmith", Tag.BloodyHarvest|Tag.VeryLongMission|Tag.UniqueEnemy|Tag.MissionLocation),
    SeedEntry("Enemy: Pumpkin Kingpin/Jacques O'Lantern", Tag.BloodyHarvest|Tag.SlowEnemy),
    SeedEntry("Mission: Trick or Treat", Tag.BloodyHarvest|Tag.ShortMission),
    SeedEntry("Enemy: Clark the Combusted Cryptkeeper", Tag.BloodyHarvest|Tag.VeryLongMission|Tag.SlowEnemy|Tag.MissionLocation),
    SeedEntry("Mission: Fun, Sun, and Guns", Tag.SonOfCrawmerax|Tag.VeryLongMission),
    SeedEntry("Enemy: Son of Crawmerax the Invincible", Tag.SonOfCrawmerax|Tag.VeryLongMission|Tag.UniqueEnemy|Tag.MissionLocation),
    SeedEntry("Enemy: The Invincible Son of Crawmerax the Invincible", Tag.SonOfCrawmerax|Tag.UniqueEnemy|Tag.Raid),
    SeedEntry("Mission: Victims of Vault Hunters", Tag.SonOfCrawmerax|Tag.LongMission),
    SeedEntry("Enemy: Sparky, Son of Flynt", Tag.SonOfCrawmerax|Tag.SlowEnemy),
    SeedEntry("Mission: A Match Made on Pandora", Tag.WeddingDayMassacre|Tag.VeryLongMission),
    SeedEntry("Other: Loot Leprechaun", Tag.WeddingDayMassacre|Tag.Miscellaneous),
    SeedEntry("Enemy: BLNG Loader", Tag.WeddingDayMassacre|Tag.VeryLongMission|Tag.UniqueEnemy|Tag.MissionLocation),
    SeedEntry("Enemy: Colin Zaford", Tag.WeddingDayMassacre|Tag.SlowEnemy),
    SeedEntry("Enemy: Bridget Hodunk", Tag.WeddingDayMassacre|Tag.SlowEnemy),
    SeedEntry("Enemy: Sigmand", Tag.WeddingDayMassacre|Tag.UniqueEnemy),
    SeedEntry("Enemy: Ikaroa", Tag.WeddingDayMassacre|Tag.UniqueEnemy),
    SeedEntry("Enemy: Moby", Tag.WeddingDayMassacre|Tag.SlowEnemy),
    SeedEntry("Enemy: Fire Crak'n", Tag.WeddingDayMassacre|Tag.SlowEnemy),
    SeedEntry("Enemy: Rue, The Love Thresher", Tag.WeddingDayMassacre|Tag.SlowEnemy),
    SeedEntry("Mission: Learning to Love", Tag.WeddingDayMassacre|Tag.LongMission),
    SeedEntry("Enemy: Ed", Tag.WeddingDayMassacre|Tag.LongMission|Tag.UniqueEnemy|Tag.MissionLocation),
    SeedEntry("Enemy: Stella", Tag.WeddingDayMassacre|Tag.LongMission|Tag.UniqueEnemy|Tag.MissionLocation),
    SeedEntry("Enemy: Innuendobot 5000", Tag.WeddingDayMassacre|Tag.LongMission|Tag.UniqueEnemy|Tag.MissionLocation),
    SeedEntry("Mission: Dr. T and the Vault Hunters", Tag.DigistructPeak|Tag.ShortMission|Tag.Freebie),
    SeedEntry("Mission: A History of Simulated Violence", Tag.DigistructPeak|Tag.VeryLongMission),
    SeedEntry("Enemy: Digistruct Assassin Wot", Tag.DigistructPeak|Tag.DigistructEnemy),
    SeedEntry("Enemy: Digistruct Assassin Oney", Tag.DigistructPeak|Tag.DigistructEnemy),
    SeedEntry("Enemy: Digistruct Assassin Reeth", Tag.DigistructPeak|Tag.DigistructEnemy),
    SeedEntry("Enemy: Digistruct Assassin Rouf", Tag.DigistructPeak|Tag.DigistructEnemy),
    SeedEntry("Mission: More History of Simulated Violence", Tag.DigistructPeak|Tag.VeryLongMission),
    SeedEntry("Enemy: Digistruct Scorch", Tag.DigistructPeak|Tag.DigistructEnemy),
    SeedEntry("Enemy: Digistruct Black Queen", Tag.DigistructPeak|Tag.DigistructEnemy),
    SeedEntry("Enemy: Bone Head v3.0", Tag.DigistructPeak|Tag.DigistructEnemy),
    SeedEntry("Enemy: Digistruct Doc Mercy", Tag.DigistructPeak|Tag.DigistructEnemy),
    SeedEntry("Enemy: Digistruct Dukino's Mom", Tag.DigistructPeak|Tag.DigistructEnemy),
    SeedEntry("Enemy: 010011110100110101000111-010101110101010001001000", Tag.DigistructPeak|Tag.DigistructEnemy),
    SeedEntry("Enemy: Saturn v2.0", Tag.DigistructPeak|Tag.DigistructEnemy),
)
